/**
 * The six views of the subject in a 3 × 2 grid: the front (the source image,
 * read-only) and back / left / right / top / bottom, each uploaded by hand
 * (file picker or drag & drop) or generated by AI from the front. Full 3D
 * drivers use every view given. Pure: the shell owns the images and jobs.
 *
 * Hand-made views rarely share the front's framing, so each filled slot
 * shows a consistency badge (the shell's pre-run registration against the
 * front), an "Align" panel with an overlay, offset / scale / flip sliders
 * and a trust choice (shape + colour / colour only / off), and every other
 * slot a "Copy prompt" button giving an English prompt with the front's
 * exact framing for the user's own image tool.
 */
import { useEffect, useId, useMemo, useRef, useState, type CSSProperties, type DragEvent, type ReactNode } from 'react';
import type { I18nText, Mask, Progress, RGBAImage, ViewAlign, ViewId, ViewTrust } from '../../core/types';
import { DEFAULT_VIEW_ALIGN } from '../../core/types';
import { hasTransparency, maskFromAlpha, mirrorMask } from '../../core/image/ops';
import { maskBBox, type MaskSource, type PixelBox } from '../../core/fusion/frame';
import { SHARED_AXES, alignLevel, alignNoteText, alignResidual, alignScore, alignedBox, slotCap } from '../../core/fusion/align';
import type { AlignLevel, ViewAlignment } from '../../core/fusion/types';
import { VIEW_LABELS } from '../../ai/views';
import { throttleLatest, type Throttled } from '../../app/throttle';
import { useI18n } from '../i18n';
import { RGBACanvas } from '../RGBACanvas';
import { ProgressBar } from '../GeneratePanel';
import { Switch } from '../ParamField';
import { IconAlert, IconInfo, IconUpload, IconWand, IconX } from '../icons';
import { IconAlign, IconCheckSmall, IconCopy, IconCross, IconSettings, IconTilde, IconViews } from './icons';
import { OTHER_VIEW_IDS, missingViews, type OtherViewId, type ViewSlotInfo } from './types';
import './ai.css';

export const VIEW_TEXT = {
  title: { tr: 'Görünümler', en: 'Views' },
  intro: {
    tr: 'Tam 3B için her yön gerekir. Eksik görünümleri kendiniz yükleyin ya da yapay zekâya ürettirin.',
    en: 'Full 3D needs every side. Upload the missing views yourself or let AI generate them.',
  },
  count: { tr: '{n}/6 görünüm', en: '{n}/6 views' },
  source: { tr: 'Kaynak', en: 'Source' },
  uploaded: { tr: 'Yüklendi', en: 'Uploaded' },
  ai: { tr: 'AI', en: 'AI' },
  empty: { tr: 'Boş', en: 'Empty' },
  noFront: { tr: 'Önce görsel yükleyin', en: 'Upload an image first' },
  drop: { tr: 'Bırakın', en: 'Drop here' },
  upload: { tr: 'Yükle', en: 'Upload' },
  uploadView: { tr: '{view} görünümü yükle', en: 'Upload the {view} view' },
  generate: { tr: 'AI ile üret', en: 'Generate with AI' },
  regenerate: { tr: 'AI ile yeniden üret', en: 'Regenerate with AI' },
  generateView: { tr: '{view} görünümü AI ile üret', en: 'Generate the {view} view with AI' },
  clear: { tr: 'Temizle', en: 'Clear' },
  clearView: { tr: '{view} görünümü temizle', en: 'Clear the {view} view' },
  generating: { tr: 'Üretiliyor…', en: 'Generating…' },
  generateMissing: { tr: 'Eksik görünümleri üret ({n})', en: 'Generate missing views ({n})' },
  allPresent: { tr: 'Tüm görünümler hazır', en: 'All views are there' },
  cancel: { tr: 'İptal', en: 'Cancel' },
  aiNotReady: { tr: 'Yapay zekâ hazır değil', en: 'AI is not ready' },
  settings: { tr: 'AI sağlayıcıları…', en: 'AI providers…' },
  manual: { tr: 'Görünümleri elle yüklemek her zaman mümkün.', en: 'You can always upload views by hand.' },
  needFront: { tr: 'Önce ön görünüm (kaynak görsel) gerekir.', en: 'The front view (source image) is needed first.' },
  errorTitle: { tr: 'Görünüm üretilemedi', en: 'Could not generate the view' },
  nextFusion: { tr: 'Sonraki: çok görünümlü birleştirmeyle tam 3B', en: 'Next: full 3D with multi-view fusion' },
  nextFusionHint: {
    tr: 'Seçili sürücü yalnızca ön görseli kullanır; bu görünümleri kullanan sürücüye geçer.',
    en: 'The selected driver only uses the front image; this switches to the driver that uses these views.',
  },
  hintDefault: {
    tr: 'Tüm görünümler dik, ortalanmış ve aynı ölçekte olmalı. Bir kutunun üzerine gelin ya da odaklanın: hangi yönden bakıldığını gösterir.',
    en: 'All views should be upright, centred and at the same scale. Hover or focus a slot to see where its camera is.',
  },
  // Consistency / alignment
  check: { tr: 'Tutarlılık', en: 'Consistency' },
  checkLabel: { tr: 'Tutarlılık %{score}, {level}: {note}', en: 'Consistency {score} %, {level}: {note}' },
  align: { tr: 'Hizala', en: 'Align' },
  alignView: { tr: '{view} görünümü hizala', en: 'Align the {view} view' },
  offsetX: { tr: 'Yatay kayma', en: 'Offset X' },
  offsetY: { tr: 'Dikey kayma', en: 'Offset Y' },
  scale: { tr: 'Ölçek', en: 'Scale' },
  flip: { tr: 'Yatay aynala', en: 'Flip horizontally' },
  useFor: { tr: 'Bu görünüm ne için kullanılsın', en: 'Use this view for' },
  trustFull: { tr: 'Şekil + renk', en: 'Shape + colour' },
  trustColor: { tr: 'Yalnız renk', en: 'Colour only' },
  trustOff: { tr: 'Kapalı', en: 'Off' },
  autoAlign: { tr: 'Otomatik hizala', en: 'Auto-align' },
  autoAlignOff: { tr: 'Bu görünüm önle eşleştirilemedi', en: 'Could not match this view to the front' },
  resetAlign: { tr: 'Sıfırla', en: 'Reset' },
  close: { tr: 'Kapat', en: 'Close' },
  copyPrompt: { tr: 'İstemi kopyala', en: 'Copy prompt' },
  copyPromptView: { tr: '{view} görünümü için istemi kopyala (İngilizce)', en: 'Copy the prompt for the {view} view' },
  copied: {
    tr: 'İstem kopyalandı — ön görselle birlikte görsel aracınıza yapıştırın',
    en: 'Prompt copied — paste it into your image tool together with the front image',
  },
  copyFailed: { tr: 'Panoya yazılamadı; metni aşağıdan seçip kopyalayın', en: 'Could not write to the clipboard; select and copy the text below' },
  selectAll: { tr: 'Tümünü seç', en: 'Select all' },
  levelGood: { tr: 'iyi', en: 'good' },
  levelFair: { tr: 'orta', en: 'fair' },
  levelPoor: { tr: 'zayıf', en: 'poor' },
  pending: { tr: 'Kontrol ediliyor…', en: 'Checking…' },
  legend: {
    tr: 'Gri: önden beklenen · Renkli: bu görünüm · Kesikli: ön görünümün işaret satırları',
    en: 'Grey: expected from the front · Colour: this view · Dashed: landmarks of the front',
  },
  guideTitle: { tr: 'Görünümleri tutarlı yapmak için', en: 'Making views consistent' },
  guide1: {
    tr: 'Aynı yükseklik ve ölçek; hiçbir şey kesilmesin (ayaklar, eller, saç çerçevenin içinde).',
    en: 'Same height and scale; nothing cropped (feet, hands and hair inside the frame).',
  },
  guide2: { tr: 'Ortografik (perspektifsiz) kamera, düz arka plan.', en: 'Orthographic camera (no perspective), plain background.' },
  guide3: { tr: 'Aynı poz — önce T-poz uygulayın.', en: 'Same pose — apply the T-pose first.' },
  guide4: {
    tr: 'Kollar ya da bacaklar kaybolursa: Hizala → Otomatik hizala, ya da "Yalnız renk".',
    en: 'If arms or legs vanish: Align → Auto-align, or "Colour only".',
  },
  guidePrompt: {
    tr: 'Boş bir yuvadaki "İstemi kopyala", ön görselinizin tam çerçevesiyle İngilizce bir istem verir; görsel aracınıza ön görselle birlikte yapıştırın.',
    en: 'Use Copy prompt on an empty slot for an English prompt with your front image\'s exact framing; paste it into your image tool together with the front image.',
  },
  promptLang: { tr: 'İstem İngilizce\'dir; ön görselinizle birlikte yapıştırın.', en: 'The prompt is in English; paste it together with your front image.' },
} satisfies Record<string, I18nText>;

/** Where each view's camera is (matches the ViewId conventions in src/core/types.ts). */
export const VIEW_HINTS: Record<ViewId, I18nText> = {
  front: { tr: 'Ön: kaynak görsel, konu kameraya bakıyor.', en: 'Front: the source image, the subject facing the camera.' },
  back: { tr: 'Arka: arkadan görünüm — öznenin sol yanı görselin solunda.', en: 'Back: seen from behind — the subject’s left side on the image’s left.' },
  left: { tr: 'Sol: öznenin sol yanı (kamera öznenin solunda).', en: 'Left: the subject’s left side (camera at the subject’s left).' },
  right: { tr: 'Sağ: öznenin sağ yanı (kamera öznenin sağında).', en: 'Right: the subject’s right side (camera at the subject’s right).' },
  top: { tr: 'Üst: yukarıdan görünüm — öznenin önü görselin altında.', en: 'Top: seen from above — the subject’s front at the image bottom.' },
  bottom: { tr: 'Alt: aşağıdan görünüm — öznenin önü görselin üstünde.', en: 'Bottom: seen from below — the subject’s front at the image top.' },
};

const T = VIEW_TEXT;
const ORDER: ViewId[] = ['front', ...OTHER_VIEW_IDS];
const TRUSTS: ViewTrust[] = ['full', 'color', 'off'];
const LEVEL_TEXT: Record<AlignLevel, I18nText> = { good: T.levelGood, fair: T.levelFair, poor: T.levelPoor };
const IDENTITY = { dx: 0, dy: 0, scale: 1 };

/** Slider ranges in percent (stored as fractions). */
export const ALIGN_SLIDERS = {
  dx: { min: -20, max: 20, step: 0.5 },
  dy: { min: -20, max: 20, step: 0.5 },
  scale: { min: 70, max: 140, step: 1 },
} as const;

/** Below this registration confidence "Auto-align" is offered no more. */
export const AUTO_ALIGN_MIN_CONFIDENCE = 0.45;

interface Props {
  front: RGBAImage | null;
  views: Partial<Record<OtherViewId, ViewSlotInfo>>;
  onUpload: (view: OtherViewId, file: File) => void;
  onGenerate: (view: OtherViewId) => void;
  onGenerateMissing: () => void;
  onClear: (view: OtherViewId) => void;
  busy: ViewId | 'all' | null;
  progress: Progress | null;
  error: I18nText | null;
  onCancel: () => void;
  aiReady: boolean;
  aiReason: string | null;
  onOpenSettings: () => void;
  disabled?: boolean;
  /** Set when views are given but the selected driver ignores them: switch to multi-view fusion (and go on). */
  onUseFusion?: () => void;
  /** Pre-run registration of each view against the front (absent while checking); omit to hide the badges. */
  checks?: Partial<Record<OtherViewId, ViewAlignment>>;
  onAlign?: (view: OtherViewId, patch: Partial<ViewAlign>) => void;
  onAlignAuto?: (view: OtherViewId) => void;
  onAlignReset?: (view: OtherViewId) => void;
  /** The front's foreground mask for the alignment overlay (null = alpha / whole image). */
  frontMask?: Mask | null;
  /** Prompt text for a slot (null hides the Copy prompt button). */
  prompt?: (view: OtherViewId) => string | null;
}

/** The first image among dropped files (or the first file). */
function droppedImage(e: DragEvent): File | null {
  const files = Array.from(e.dataTransfer.files);
  return files.find((f) => f.type.startsWith('image/')) ?? files[0] ?? null;
}

/**
 * Score / level shown for a view now: the check's own while the alignment
 * is automatic, else re-scored from the check's suggestion and the current
 * manual correction (alignResidual / alignScore, no core re-run).
 */
export function liveAlignment(check: ViewAlignment, align: ViewAlign): { score: number; level: AlignLevel } {
  const manual = align.mode === 'manual';
  if (!manual && check.status !== 'manual') return { score: check.score, level: check.level };
  const residual = alignResidual(check.suggested, manual ? align : check.suggested);
  const maskSource: MaskSource = check.notes.some((n) => n.code === 'noMask') ? 'none' : 'given';
  // The slot checks (wrong slot, facing, duplicate) hold whatever the placement.
  const score = alignScore({ confidence: check.confidence, residual, cut: check.cut, status: manual ? 'manual' : 'aligned', id: check.id, maskSource, cap: slotCap(check.notes) });
  return { score, level: alignLevel(score) };
}

/** The correction the fusion would apply now (manual values, else the registration's). */
export function currentCorrection(check: ViewAlignment | undefined, align: ViewAlign): { dx: number; dy: number; scale: number } {
  if (align.mode === 'manual') return { dx: align.dx, dy: align.dy, scale: align.scale };
  if (!check) return IDENTITY;
  const c = check.status === 'manual' ? check.suggested : check.applied;
  return { dx: c.dx, dy: c.dy, scale: c.scale };
}

/** The silhouette bbox back from a fitted box (inverse of alignedBox). */
export function bboxOfFit(fit: PixelBox, a: { dx: number; dy: number; scale: number }, shared: { x: boolean; y: boolean }): PixelBox {
  const bw = (fit.x1 - fit.x0) * (shared.x ? a.scale : 1), bh = (fit.y1 - fit.y0) * (shared.y ? a.scale : 1);
  const L = Math.max(bw, bh);
  const cx = (fit.x0 + fit.x1) / 2 + a.dx * L, cy = (fit.y0 + fit.y1) / 2 + a.dy * L;
  return { x0: cx - bw / 2, y0: cy - bh / 2, x1: cx + bw / 2, y1: cy + bh / 2 };
}

export function ViewsPanel(p: Props) {
  const { tx, lang } = useI18n();
  const id = useId();
  const [hint, setHint] = useState<ViewId | null>(null);
  const [notice, setNotice] = useState<'copied' | 'failed' | null>(null);
  const [fallback, setFallback] = useState<string | null>(null);
  const [alignOpen, setAlignOpen] = useState<OtherViewId | null>(null);
  const triggers = useRef<Partial<Record<OtherViewId, HTMLButtonElement | null>>>({});
  const textRef = useRef<HTMLTextAreaElement>(null);
  const busy = p.busy !== null;
  const lock = !!p.disabled;
  const missing = missingViews(p.views);
  const filled = (p.front ? 1 : 0) + OTHER_VIEW_IDS.length - missing.length;
  const canAi = p.aiReady && !!p.front && !busy && !lock;
  // The panel closes with its view (cleared meanwhile) or when the shell cannot align.
  const open = alignOpen && p.views[alignOpen] && p.onAlign ? alignOpen : null;
  const panelId = `${id}-align`;

  // A copy notice fades after a while (the hint takes the line back).
  useEffect(() => {
    if (!notice) return;
    const t = window.setTimeout(() => setNotice(null), 8000);
    return () => window.clearTimeout(t);
  }, [notice]);

  const copyPrompt = async (view: OtherViewId) => {
    const text = p.prompt?.(view);
    if (!text) return;
    let ok = false;
    try {
      const clipboard = typeof navigator !== 'undefined' ? navigator.clipboard : undefined;
      if (clipboard?.writeText) {
        await clipboard.writeText(text);
        ok = true;
      }
    } catch {
      ok = false;
    }
    if (ok) {
      setFallback(null);
      setNotice('copied');
    } else {
      setFallback(text);
      setNotice('failed');
    }
  };

  const toggleAlign = (view: OtherViewId) => setAlignOpen((cur) => (cur === view ? null : view));
  const closeAlign = (view: OtherViewId) => {
    setAlignOpen(null);
    triggers.current[view]?.focus();
  };

  return (
    <section className="card ai-views" aria-labelledby={`${id}-title`} data-testid="views-panel">
      <div className="card-head">
        <h2 id={`${id}-title`} className="card-title">
          <IconViews /> {tx(T.title)}
        </h2>
        <span className={`pill${filled === 6 ? ' pill-live' : ''} tabular`} data-testid="views-count">
          {tx(T.count, { n: filled })}
        </span>
      </div>
      <p className="muted small">{tx(T.intro)}</p>

      {!p.aiReady && (
        <div className="ai-callout" data-testid="views-ai-reason">
          <IconInfo size={16} />
          <div className="ai-callout-body small">
            <strong>{tx(T.aiNotReady)}</strong>
            {p.aiReason && <span>{p.aiReason}</span>}
            <span className="muted">{tx(T.manual)}</span>
          </div>
          <button type="button" className="btn btn-secondary btn-sm" onClick={p.onOpenSettings} data-testid="views-settings">
            <IconSettings size={14} /> {tx(T.settings)}
          </button>
        </div>
      )}

      <ul className="ai-view-grid" aria-describedby={`${id}-hint`}>
        {ORDER.map((view) =>
          view === 'front' ? (
            <FrontSlot key={view} image={p.front} busy={p.busy === 'front'} onHint={setHint} />
          ) : (
            <ViewSlot
              key={view}
              view={view}
              info={p.views[view] ?? null}
              busy={p.busy === view || (p.busy === 'all' && !p.views[view])}
              progress={p.busy === view ? p.progress : null}
              lock={lock || busy}
              canAi={canAi}
              aiTitle={!p.aiReady ? p.aiReason ?? tx(T.aiNotReady) : !p.front ? tx(T.needFront) : undefined}
              onUpload={(f) => p.onUpload(view, f)}
              onGenerate={() => p.onGenerate(view)}
              onClear={() => p.onClear(view)}
              onHint={setHint}
              check={p.checks?.[view]}
              showCheck={p.checks !== undefined}
              alignOpen={open === view}
              alignPanelId={panelId}
              onAlignToggle={p.onAlign ? () => toggleAlign(view) : undefined}
              triggerRef={(el) => {
                triggers.current[view] = el;
              }}
              onCopy={p.prompt && p.front ? () => void copyPrompt(view) : undefined}
            />
          ),
        )}
      </ul>

      <p id={`${id}-hint`} className={`ai-view-hint small${notice ? ' is-notice' : ''}`} aria-live="polite" data-testid="views-hint">
        {notice ? <IconInfo size={14} /> : hint ? <ViewDiagram view={hint} size={20} /> : <IconInfo size={14} />}
        <span>{notice === 'copied' ? tx(T.copied) : notice === 'failed' ? tx(T.copyFailed) : tx(hint ? VIEW_HINTS[hint] : T.hintDefault)}</span>
      </p>

      {fallback && (
        <div className="ai-prompt-text" data-testid="view-prompt-fallback">
          <textarea ref={textRef} className="input ai-textarea" readOnly rows={6} value={fallback} data-testid="view-prompt-text" aria-label={tx(T.copyPrompt)} />
          <div className="ai-prompt-text-row">
            <span className="muted small grow">{tx(T.promptLang)}</span>
            <button type="button" className="btn btn-secondary btn-sm" onClick={() => textRef.current?.select()} data-testid="view-prompt-select">
              {tx(T.selectAll)}
            </button>
            <button type="button" className="icon-btn" onClick={() => setFallback(null)} aria-label={tx(T.close)} title={tx(T.close)}>
              <IconX size={14} />
            </button>
          </div>
        </div>
      )}

      {open && p.views[open] && p.onAlign && (
        <AlignPanel
          id={panelId}
          view={open}
          info={p.views[open]!}
          front={p.front}
          frontMask={p.frontMask ?? null}
          check={p.checks?.[open]}
          onAlign={p.onAlign}
          onAuto={p.onAlignAuto}
          onReset={p.onAlignReset}
          onClose={() => closeAlign(open)}
          lang={lang}
        />
      )}

      <details className="ai-guide" data-testid="views-guide">
        <summary className="small">
          <IconInfo size={14} /> {tx(T.guideTitle)}
        </summary>
        <ol className="small">
          <li>{tx(T.guide1)}</li>
          <li>{tx(T.guide2)}</li>
          <li>{tx(T.guide3)}</li>
          <li>{tx(T.guide4)}</li>
        </ol>
        <p className="small muted">{tx(T.guidePrompt)}</p>
      </details>

      {busy ? (
        <div className="ai-run">
          <div className="generate-row">
            <button type="button" className="btn btn-primary grow" disabled aria-busy="true">
              <span className="spinner" aria-hidden="true" /> {tx(T.generating)}
            </button>
            <button type="button" className="btn btn-secondary" onClick={p.onCancel} data-testid="views-cancel">
              <IconX size={16} /> {tx(T.cancel)}
            </button>
          </div>
          <ProgressBar progress={p.progress} testId="views-progress" />
        </div>
      ) : (
        <button
          type="button"
          className="btn btn-primary btn-block ai-wrap-btn"
          onClick={p.onGenerateMissing}
          disabled={!canAi || missing.length === 0}
          title={!p.aiReady ? p.aiReason ?? tx(T.aiNotReady) : !p.front ? tx(T.needFront) : undefined}
          data-testid="views-generate-missing"
        >
          <IconWand size={16} /> {missing.length ? tx(T.generateMissing, { n: missing.length }) : tx(T.allPresent)}
        </button>
      )}
      {!busy && p.aiReady && !p.front && <p className="muted small center">{tx(T.needFront)}</p>}
      {!busy && p.onUseFusion && missing.length < OTHER_VIEW_IDS.length && (
        <button
          type="button"
          className="btn btn-secondary btn-block ai-wrap-btn"
          onClick={p.onUseFusion}
          disabled={lock}
          title={tx(T.nextFusionHint)}
          data-testid="views-use-fusion"
        >
          <IconViews /> {tx(T.nextFusion)}
        </button>
      )}

      {p.error && !busy && (
        <div className="alert alert-danger" role="alert" data-testid="views-error">
          <IconAlert size={18} />
          <div className="alert-body">
            <strong>{tx(T.errorTitle)}</strong>
            <p>{tx(p.error)}</p>
          </div>
        </div>
      )}
    </section>
  );
}

function SlotHead({ view, children }: { view: ViewId; children?: ReactNode }) {
  const { tx } = useI18n();
  return (
    <div className="ai-slot-head">
      <ViewDiagram view={view} />
      <span className="ai-slot-name" title={tx(VIEW_LABELS[view])}>{tx(VIEW_LABELS[view])}</span>
      {children}
    </div>
  );
}

function OriginBadge({ kind, children }: { kind: 'source' | 'upload' | 'ai'; children: ReactNode }) {
  return <span className={`ai-origin is-${kind}`}>{children}</span>;
}

function FrontSlot({ image, busy, onHint }: { image: RGBAImage | null; busy: boolean; onHint: (v: ViewId | null) => void }) {
  const { tx } = useI18n();
  return (
    <li
      className={`ai-slot is-front${busy ? ' is-busy' : ''}`}
      aria-busy={busy || undefined}
      data-testid="view-front"
      data-filled={image ? 'true' : 'false'}
      onMouseEnter={() => onHint('front')}
      onMouseLeave={() => onHint(null)}
      title={tx(VIEW_HINTS.front)}
    >
      <SlotHead view="front" />
      <div className="ai-slot-thumb checker">
        {image ? (
          <>
            <RGBACanvas image={image} className="ai-slot-img" label={tx(VIEW_LABELS.front)} />
            <OriginBadge kind="source">{tx(T.source)}</OriginBadge>
          </>
        ) : (
          <span className="ai-slot-empty">
            <span>{tx(T.noFront)}</span>
          </span>
        )}
        {busy && (
          <span className="ai-slot-busy">
            <span className="spinner" aria-hidden="true" />
          </span>
        )}
      </div>
      <div className="ai-slot-actions">
        <span className="ai-slot-meta tabular">{image ? `${image.width} × ${image.height}` : '—'}</span>
      </div>
    </li>
  );
}

/** Consistency badge of a filled slot: level icon + score (never colour alone), "…" while the check runs. */
function CheckBadge({ view, check, align }: { view: OtherViewId; check: ViewAlignment | undefined; align: ViewAlign }) {
  const { tx, lang } = useI18n();
  if (!check) {
    const pending = tx(T.pending);
    return (
      <span className="ai-check is-pending" data-testid={`view-check-${view}`} data-level="pending" aria-busy="true" role="img" aria-label={pending} title={pending}>
        …
      </span>
    );
  }
  const live = liveAlignment(check, align);
  const note = alignNoteText(check, lang);
  const cut = (['top', 'bottom', 'left', 'right'] as const).filter((e) => check.cut[e]).join(',');
  const label = tx(T.checkLabel, { score: live.score, level: tx(LEVEL_TEXT[live.level]), note });
  const Icon = live.level === 'good' ? IconCheckSmall : live.level === 'fair' ? IconTilde : IconCross;
  return (
    <span
      className={`ai-check is-${live.level}`}
      data-testid={`view-check-${view}`}
      data-level={live.level}
      data-score={live.score}
      data-cut={cut}
      role="img"
      aria-label={label}
      title={note}
    >
      <Icon size={11} /> <span className="tabular">{live.score}</span>
    </span>
  );
}

function ViewSlot({
  view,
  info,
  busy,
  progress,
  lock,
  canAi,
  aiTitle,
  onUpload,
  onGenerate,
  onClear,
  onHint,
  check,
  showCheck,
  alignOpen,
  alignPanelId,
  onAlignToggle,
  triggerRef,
  onCopy,
}: {
  view: OtherViewId;
  info: ViewSlotInfo | null;
  busy: boolean;
  progress: Progress | null;
  lock: boolean;
  canAi: boolean;
  aiTitle: string | undefined;
  onUpload: (file: File) => void;
  onGenerate: () => void;
  onClear: () => void;
  onHint: (v: ViewId | null) => void;
  check: ViewAlignment | undefined;
  showCheck: boolean;
  alignOpen: boolean;
  alignPanelId: string;
  onAlignToggle?: () => void;
  triggerRef: (el: HTMLButtonElement | null) => void;
  onCopy?: () => void;
}) {
  const { tx, lang } = useI18n();
  const [dragging, setDragging] = useState(false);
  const name = tx(VIEW_LABELS[view]);
  const nameLower = name.toLocaleLowerCase(lang === 'tr' ? 'tr-TR' : 'en-US');
  const pct = progress && typeof progress.ratio === 'number' && Number.isFinite(progress.ratio) ? Math.round(Math.min(1, Math.max(0, progress.ratio)) * 100) : null;
  const align = info?.align ?? DEFAULT_VIEW_ALIGN;
  const trust = info ? align.trust : 'full';

  const dragProps = lock
    ? {}
    : {
        onDragOver: (e: DragEvent) => {
          if (!Array.from(e.dataTransfer.types).includes('Files')) return;
          e.preventDefault();
          e.dataTransfer.dropEffect = 'copy';
          setDragging(true);
        },
        onDragLeave: () => setDragging(false),
        onDrop: (e: DragEvent) => {
          e.preventDefault();
          setDragging(false);
          const file = droppedImage(e);
          if (file) onUpload(file);
        },
      };

  return (
    <li
      className={`ai-slot${dragging ? ' is-dragging' : ''}${busy ? ' is-busy' : ''}${trust === 'off' ? ' is-off' : ''}`}
      data-testid={`view-${view}`}
      data-filled={info ? 'true' : 'false'}
      data-origin={info?.origin}
      data-trust={info ? trust : undefined}
      aria-busy={busy || undefined}
      onMouseEnter={() => onHint(view)}
      onMouseLeave={() => onHint(null)}
      onFocus={() => onHint(view)}
      onBlur={() => onHint(null)}
      {...dragProps}
    >
      <SlotHead view={view}>{info && showCheck && trust !== 'off' && <CheckBadge view={view} check={check} align={align} />}</SlotHead>
      <div className="ai-slot-thumb checker" title={info ? info.name : tx(VIEW_HINTS[view])}>
        {info ? (
          <>
            <RGBACanvas image={info.image} className="ai-slot-img" label={`${name}: ${info.name}`} />
            <OriginBadge kind={info.origin}>{tx(info.origin === 'ai' ? T.ai : T.uploaded)}</OriginBadge>
            {trust !== 'full' && (
              <span className={`ai-trust-badge is-${trust}`} data-testid={`view-trust-${view}`}>
                {tx(trust === 'color' ? T.trustColor : T.trustOff)}
              </span>
            )}
          </>
        ) : busy ? null : (
          <span className="ai-slot-empty">
            <IconUpload size={16} />
            <span>{dragging ? tx(T.drop) : tx(T.empty)}</span>
          </span>
        )}
        {busy && (
          <span className="ai-slot-busy">
            <span className="spinner" aria-hidden="true" />
            {pct !== null && <span className="tabular small">{pct}%</span>}
          </span>
        )}
      </div>
      <div className="ai-slot-actions">
        <label className={`icon-btn ai-slot-btn${lock ? ' is-disabled' : ''}`} title={tx(T.uploadView, { view: nameLower })} data-testid={`view-upload-${view}`}>
          <input
            type="file"
            accept="image/png,image/jpeg,image/webp,image/*"
            className="visually-hidden"
            disabled={lock}
            aria-label={tx(T.uploadView, { view: nameLower })}
            onChange={(e) => {
              const file = e.target.files?.[0];
              if (file) onUpload(file);
              e.target.value = '';
            }}
          />
          <IconUpload size={15} />
        </label>
        <button
          type="button"
          className="icon-btn ai-slot-btn is-ai"
          onClick={onGenerate}
          disabled={!canAi}
          aria-label={tx(info ? T.regenerate : T.generateView, { view: nameLower })}
          title={aiTitle ?? tx(info ? T.regenerate : T.generateView, { view: nameLower })}
          data-testid={`view-generate-${view}`}
        >
          <IconWand size={15} />
        </button>
        {onCopy && (
          <button
            type="button"
            className="icon-btn ai-slot-btn"
            onClick={onCopy}
            aria-label={tx(T.copyPromptView, { view: nameLower })}
            title={tx(T.copyPromptView, { view: nameLower })}
            data-testid={`view-prompt-${view}`}
          >
            <IconCopy size={15} />
          </button>
        )}
        {info && onAlignToggle && (
          <button
            type="button"
            ref={triggerRef}
            className={`icon-btn ai-slot-btn${alignOpen ? ' is-on' : ''}`}
            onClick={onAlignToggle}
            aria-expanded={alignOpen}
            aria-controls={alignPanelId}
            aria-label={tx(T.alignView, { view: nameLower })}
            title={tx(T.alignView, { view: nameLower })}
            data-testid={`view-align-${view}`}
          >
            <IconAlign size={15} />
          </button>
        )}
        {info && (
          <button
            type="button"
            className="icon-btn ai-slot-btn"
            onClick={onClear}
            disabled={lock}
            aria-label={tx(T.clearView, { view: nameLower })}
            title={tx(T.clearView, { view: nameLower })}
            data-testid={`view-clear-${view}`}
          >
            <IconX size={15} />
          </button>
        )}
      </div>
    </li>
  );
}

// ---------------------------------------------------------------- Align panel

type SliderKey = 'dx' | 'dy' | 'scale';

function AlignPanel({
  id,
  view,
  info,
  front,
  frontMask,
  check,
  onAlign,
  onAuto,
  onReset,
  onClose,
  lang,
}: {
  id: string;
  view: OtherViewId;
  info: ViewSlotInfo;
  front: RGBAImage | null;
  frontMask: Mask | null;
  check: ViewAlignment | undefined;
  onAlign: (view: OtherViewId, patch: Partial<ViewAlign>) => void;
  onAuto?: (view: OtherViewId) => void;
  onReset?: (view: OtherViewId) => void;
  onClose: () => void;
  lang: 'tr' | 'en';
}) {
  const { tx } = useI18n();
  const uid = useId();
  const root = useRef<HTMLDivElement>(null);
  const align = info.align ?? DEFAULT_VIEW_ALIGN;
  const shared = SHARED_AXES[view];
  const locale = lang === 'tr' ? 'tr-TR' : 'en-US';
  const name = tx(VIEW_LABELS[view]).toLocaleLowerCase(locale);
  // "Align the back view" / "Arka görünümü hizala": the Turkish title starts with the view's name.
  const title = tx(T.alignView, { view: name });
  const heading = title.charAt(0).toLocaleUpperCase(locale) + title.slice(1);
  const current = currentCorrection(check, align);
  const live = check ? liveAlignment(check, align) : null;
  const status = live && check ? `${live.score} · ${tx(LEVEL_TEXT[live.level])} · ${alignNoteText(check, lang)}` : tx(T.pending);
  // "Auto-align" returns to the registration's result: pointless only while the view is automatic and the
  // registration could not match it (a check made for a manual placement scores that placement, not the match).
  const unmatched = !!check && check.status !== 'manual' && check.confidence < AUTO_ALIGN_MIN_CONFIDENCE;
  const autoOff = !check || (align.mode === 'auto' && unmatched);

  // Slider drags are coalesced to one dispatch per frame; the patch keys merge
  // meanwhile. The throttle lives with the effect (a cancelled one stays dead,
  // and StrictMode remounts effects without re-running memos); what is still
  // pending when the panel closes or switches views is dispatched at once.
  const pending = useRef<Partial<ViewAlign>>({});
  const flush = useRef<Throttled<null> | null>(null);
  useEffect(() => {
    const th = throttleLatest<null>(() => {
      const patch = pending.current;
      pending.current = {};
      if (Object.keys(patch).length) onAlign(view, patch);
    });
    flush.current = th;
    return () => {
      th.cancel();
      if (flush.current === th) flush.current = null;
      const patch = pending.current;
      pending.current = {};
      if (Object.keys(patch).length) onAlign(view, patch);
    };
  }, [onAlign, view]);
  const drag = (patch: Partial<ViewAlign>) => {
    if (!flush.current) {
      onAlign(view, patch);
      return;
    }
    pending.current = { ...pending.current, ...patch };
    flush.current.push(null);
  };
  // While the alignment is automatic the sliders start from the registration's
  // values; the first edit carries all three, so the untouched ones stay put
  // instead of snapping to the store's cached defaults.
  const edit = (k: SliderKey, v: number): Partial<ViewAlign> => (align.mode === 'manual' ? { [k]: v } : { ...current, [k]: v });

  // Opening moves focus into the panel; Escape closes it and returns focus to the trigger.
  useEffect(() => {
    root.current?.focus();
  }, [view]);

  const slider = (k: SliderKey, label: I18nText) => (
    <AlignField
      key={k}
      k={k}
      label={tx(label)}
      value={current[k]}
      onCommit={(v) => onAlign(view, edit(k, v))}
      onDrag={(v) => drag(edit(k, v))}
    />
  );

  return (
    <div
      ref={root}
      id={id}
      className="ai-align"
      role="group"
      aria-labelledby={`${uid}-title`}
      data-testid="view-align-panel"
      data-view={view}
      tabIndex={-1}
      onKeyDown={(e) => {
        if (e.key !== 'Escape') return;
        e.preventDefault();
        e.stopPropagation();
        onClose();
      }}
    >
      <div className="ai-align-head">
        <h3 id={`${uid}-title`} className="ai-align-title">
          <IconAlign size={16} /> {heading}
        </h3>
        <button type="button" className="icon-btn" onClick={onClose} aria-label={tx(T.close)} title={tx(T.close)} data-testid="align-close">
          <IconX size={16} />
        </button>
      </div>
      <div className="ai-align-grid">
        <div className="ai-align-preview">
          <AlignOverlay view={view} info={info} front={front} frontMask={frontMask} check={check} correction={current} flipX={align.flipX} label={status} />
          <p className="ai-align-legend">{tx(T.legend)}</p>
        </div>
        <div className="ai-align-controls">
          {shared.x && slider('dx', T.offsetX)}
          {shared.y && slider('dy', T.offsetY)}
          {slider('scale', T.scale)}
          <Switch id={`${uid}-flip`} checked={align.flipX} onChange={(v) => onAlign(view, { flipX: v })} label={tx(T.flip)} testId="align-flip" />
          <fieldset className="ai-trust" role="radiogroup" aria-labelledby={`${uid}-trust`} data-testid="align-trust">
            <legend id={`${uid}-trust`} className="field-label">
              {tx(T.useFor)}
            </legend>
            <div className="ai-trust-opts">
              {TRUSTS.map((tr) => (
                <label key={tr} className={`ai-trust-opt${align.trust === tr ? ' is-on' : ''}`}>
                  <input
                    type="radio"
                    name={`${uid}-trust`}
                    value={tr}
                    checked={align.trust === tr}
                    onChange={() => onAlign(view, { trust: tr })}
                    data-testid={`align-trust-${tr}`}
                  />
                  <span>{tx(tr === 'full' ? T.trustFull : tr === 'color' ? T.trustColor : T.trustOff)}</span>
                </label>
              ))}
            </div>
          </fieldset>
          <div className="ai-align-actions">
            <button
              type="button"
              className="btn btn-secondary btn-sm"
              onClick={() => onAuto?.(view)}
              disabled={autoOff || !onAuto}
              title={autoOff && unmatched ? tx(T.autoAlignOff) : undefined}
              data-testid="align-auto"
            >
              <IconAlign size={14} /> {tx(T.autoAlign)}
            </button>
            <button type="button" className="btn btn-ghost btn-sm" onClick={() => onReset?.(view)} disabled={!onReset} data-testid="align-reset">
              {tx(T.resetAlign)}
            </button>
          </div>
          <p className="ai-align-status small" aria-live="polite" data-testid="align-status">
            {status}
          </p>
        </div>
      </div>
    </div>
  );
}

/** Range slider + paired number input in percent; the number commits at once, the slider through `onDrag`. */
function AlignField({ k, label, value, onCommit, onDrag }: { k: SliderKey; label: string; value: number; onCommit: (v: number) => void; onDrag: (v: number) => void }) {
  const uid = useId();
  const r = ALIGN_SLIDERS[k];
  const [draft, setDraft] = useState<string | null>(null);
  const shown = Math.round(value * 100 * 2) / 2;
  const clamp = (v: number) => Math.min(r.max, Math.max(r.min, v));
  const commit = (text: string) => {
    const v = Number(text);
    if (text.trim() !== '' && Number.isFinite(v)) onCommit(clamp(v) / 100);
    setDraft(null);
  };
  const pct = ((shown - r.min) / (r.max - r.min)) * 100;
  return (
    <div className="field ai-align-field">
      <div className="field-row">
        <label className="field-label" htmlFor={uid}>
          {label}
        </label>
        <span className="ai-align-num">
          <input
            className="input input-num"
            type="number"
            inputMode="decimal"
            min={r.min}
            max={r.max}
            step={r.step}
            value={draft ?? String(shown)}
            aria-label={label}
            data-testid={`align-${k}`}
            onChange={(e) => {
              setDraft(e.target.value);
              const v = Number(e.target.value);
              if (e.target.value.trim() !== '' && Number.isFinite(v) && v >= r.min && v <= r.max) onCommit(v / 100);
            }}
            onBlur={(e) => commit(e.target.value)}
            onKeyDown={(e) => {
              if (e.key === 'Enter') commit((e.target as HTMLInputElement).value);
            }}
          />
          <span className="muted small">%</span>
        </span>
      </div>
      <input
        id={uid}
        className="range"
        type="range"
        min={r.min}
        max={r.max}
        step={r.step}
        value={shown}
        data-testid={`align-${k}-range`}
        style={{ '--pct': `${Math.min(100, Math.max(0, pct))}%` } as CSSProperties}
        onChange={(e) => {
          setDraft(null);
          onDrag(Number(e.target.value) / 100);
        }}
      />
    </div>
  );
}

// ---------------------------------------------------------------- Overlay

const OVERLAY_W = 256;

/** The foreground of an image: its mask, else its alpha, else everything. */
function silhouetteOf(image: RGBAImage, mask: Mask | null | undefined): Mask {
  if (mask && mask.width === image.width && mask.height === image.height) return mask;
  if (hasTransparency(image)) return maskFromAlpha(image);
  return { width: image.width, height: image.height, data: new Uint8Array(image.width * image.height).fill(1) };
}

/** A mask as a tinted canvas (transparent background). */
function maskCanvas(mask: Mask, rgb: [number, number, number], alpha: number): HTMLCanvasElement | null {
  if (typeof document === 'undefined') return null;
  const c = document.createElement('canvas');
  c.width = mask.width;
  c.height = mask.height;
  const ctx = c.getContext('2d');
  if (!ctx) return null;
  const img = ctx.createImageData(mask.width, mask.height);
  const a = Math.round(alpha * 255);
  for (let i = 0; i < mask.data.length; i++) {
    if (!mask.data[i]) continue;
    img.data[i * 4] = rgb[0];
    img.data[i * 4 + 1] = rgb[1];
    img.data[i * 4 + 2] = rgb[2];
    img.data[i * 4 + 3] = a;
  }
  ctx.putImageData(img, 0, 0);
  return c;
}

function hatch(ctx: CanvasRenderingContext2D, x: number, y: number, w: number, h: number) {
  if (w <= 0 || h <= 0) return;
  ctx.save();
  ctx.beginPath();
  ctx.rect(x, y, w, h);
  ctx.clip();
  ctx.fillStyle = 'rgba(220, 38, 38, 0.18)';
  ctx.fillRect(x, y, w, h);
  ctx.strokeStyle = 'rgba(220, 38, 38, 0.8)';
  ctx.lineWidth = 1.5;
  ctx.beginPath();
  for (let d = -h; d < w + h; d += 7) {
    ctx.moveTo(x + d, y + h);
    ctx.lineTo(x + d + h, y);
  }
  ctx.stroke();
  ctx.restore();
}

/**
 * The face of the object box this view maps onto: the front's expectation in
 * grey (its mirrored silhouette for the back; its extent lines and landmark
 * guides for sides and caps), the view's silhouette in the accent colour at
 * the current correction, red hatching where the view is cut off.
 */
function AlignOverlay({
  view,
  info,
  front,
  frontMask,
  check,
  correction,
  flipX,
  label,
}: {
  view: OtherViewId;
  info: ViewSlotInfo;
  front: RGBAImage | null;
  frontMask: Mask | null;
  check: ViewAlignment | undefined;
  correction: { dx: number; dy: number; scale: number };
  flipX: boolean;
  label: string;
}) {
  const ref = useRef<HTMLCanvasElement>(null);
  const shared = SHARED_AXES[view];
  const frontSil = useMemo(() => (front ? silhouetteOf(front, frontMask) : null), [front, frontMask]);
  const frontBox = useMemo(() => (frontSil ? maskBBox(frontSil) ?? { x0: 0, y0: 0, x1: frontSil.width, y1: frontSil.height } : null), [frontSil]);
  const viewSil = useMemo(() => {
    const m = silhouetteOf(info.image, info.mask);
    return flipX ? mirrorMask(m) : m;
  }, [info.image, info.mask, flipX]);
  const bbox = useMemo(
    () => (check ? bboxOfFit(check.fitBox, check.applied, shared) : maskBBox(viewSil) ?? { x0: 0, y0: 0, x1: viewSil.width, y1: viewSil.height }),
    [check, viewSil, shared],
  );
  const fit = alignedBox(bbox, correction, shared);
  const aspect = view === 'back' && frontBox ? (frontBox.x1 - frontBox.x0) / (frontBox.y1 - frontBox.y0) : (fit.x1 - fit.x0) / (fit.y1 - fit.y0);
  const W = OVERLAY_W;
  const H = Math.round(Math.min(512, Math.max(96, W / (Number.isFinite(aspect) && aspect > 0 ? aspect : 1))));
  const fitKey = `${fit.x0},${fit.y0},${fit.x1},${fit.y1}`;
  const cutKey = check ? `${check.cut.top}${check.cut.bottom}${check.cut.left}${check.cut.right}` : '';
  const guideKey = check ? `${check.guides.rows.join(',')}|${check.guides.cols.join(',')}` : '';

  useEffect(() => {
    const canvas = ref.current;
    if (!canvas) return;
    canvas.width = W;
    canvas.height = H;
    const ctx = canvas.getContext('2d');
    if (!ctx) return;
    ctx.clearRect(0, 0, W, H);
    ctx.fillStyle = 'rgba(127, 127, 127, 0.08)';
    ctx.fillRect(0, 0, W, H);
    const fw = fit.x1 - fit.x0, fh = fit.y1 - fit.y0;

    // Grey: what the front says this face should look like.
    if (frontSil && frontBox) {
      const fb = frontBox;
      if (view === 'back') {
        const grey = maskCanvas(frontSil, [128, 128, 128], 0.35);
        if (grey) {
          ctx.save();
          ctx.translate(W, 0);
          ctx.scale(-1, 1);
          ctx.drawImage(grey, fb.x0, fb.y0, fb.x1 - fb.x0, fb.y1 - fb.y0, 0, 0, W, H);
          ctx.restore();
        }
      } else {
        ctx.strokeStyle = 'rgba(128, 128, 128, 0.7)';
        ctx.lineWidth = 2;
        ctx.setLineDash([]);
        ctx.beginPath();
        if (shared.y) {
          ctx.moveTo(0, 1);
          ctx.lineTo(W, 1);
          ctx.moveTo(0, H - 1);
          ctx.lineTo(W, H - 1);
        } else {
          ctx.moveTo(1, 0);
          ctx.lineTo(1, H);
          ctx.moveTo(W - 1, 0);
          ctx.lineTo(W - 1, H);
        }
        ctx.stroke();
        if (check) {
          ctx.setLineDash([4, 4]);
          ctx.lineWidth = 1;
          ctx.beginPath();
          if (shared.y) {
            for (const r of check.guides.rows) {
              const y = ((r - fb.y0) / (fb.y1 - fb.y0)) * H;
              ctx.moveTo(0, y);
              ctx.lineTo(W, y);
            }
          } else {
            for (const c of check.guides.cols) {
              const x = ((c - fb.x0) / (fb.x1 - fb.x0)) * W;
              ctx.moveTo(x, 0);
              ctx.lineTo(x, H);
            }
          }
          ctx.stroke();
          ctx.setLineDash([]);
        }
      }
    }

    // Accent: this view at the current correction (its fitted box fills the face).
    const accent = maskCanvas(viewSil, [124, 92, 255], 0.5);
    if (accent && fw > 0 && fh > 0) ctx.drawImage(accent, fit.x0, fit.y0, fw, fh, 0, 0, W, H);

    // Red hatching: beyond a cut image edge nothing is known.
    if (check) {
      const { cut } = check;
      const sx = W / fw, sy = H / fh;
      const minStrip = 8;
      if (cut.top) hatch(ctx, 0, 0, W, Math.max(minStrip, (0 - fit.y0) * sy));
      if (cut.bottom) {
        const y = (viewSil.height - fit.y0) * sy;
        hatch(ctx, 0, Math.min(H - minStrip, y), W, H);
      }
      if (cut.left) hatch(ctx, 0, 0, Math.max(minStrip, (0 - fit.x0) * sx), H);
      if (cut.right) {
        const x = (viewSil.width - fit.x0) * sx;
        hatch(ctx, Math.min(W - minStrip, x), 0, W, H);
      }
    }
    // The fit / cut / guide keys stand in for their objects (recomputed every render).
  }, [W, H, view, frontSil, frontBox, viewSil, fitKey, cutKey, guideKey, shared.x, shared.y]);

  return <canvas ref={ref} className="ai-align-canvas" data-testid="align-overlay" role="img" aria-label={label} />;
}

/**
 * Tiny orientation sketch: a plan view (subject from above, facing down =
 * towards the front camera) for the four sides, an elevation for top /
 * bottom. The accent arrow is the camera looking at the subject.
 */
export function ViewDiagram({ view, size = 18 }: { view: ViewId; size?: number }) {
  const plan = view !== 'top' && view !== 'bottom';
  const camera: Record<ViewId, string> = {
    front: 'M16 31V25M13.5 27.5 16 24.5l2.5 3',
    back: 'M16 1v6M13.5 4.5 16 7.5l2.5-3',
    // The subject faces down in the sketch, so its left side is on the sketch's right.
    left: 'M31 15h-6M27.5 12.5 24.5 15l3 2.5',
    right: 'M1 15h6M4.5 12.5 7.5 15l-3 2.5',
    top: 'M16 0.5V5.5M13.5 3.5 16 6.5l2.5-3',
    bottom: 'M16 31.5v-5M13.5 28.5 16 25.5l2.5 3',
  };
  return (
    <svg className="ai-diagram" width={size} height={size} viewBox="0 0 32 32" aria-hidden="true" focusable="false">
      {plan ? (
        <g className="ai-diagram-subject">
          <circle cx="16" cy="15" r="6" />
          <path d="M14 20.2 16 23l2-2.8" />
        </g>
      ) : (
        <g className="ai-diagram-subject">
          <circle cx="16" cy="11.5" r="3.2" />
          <rect x="12.5" y="15.5" width="7" height="8.5" rx="2.5" />
        </g>
      )}
      <path className="ai-diagram-camera" d={camera[view]} />
    </svg>
  );
}
