/**
 * The six views of the subject in a 3 × 2 grid: the front (the source image,
 * read-only) and back / left / right / top / bottom, each uploaded by hand
 * (file picker or drag & drop) or generated by AI from the front. Full 3D
 * drivers use every view given. Pure: the shell owns the images and jobs.
 */
import { useId, useState, type DragEvent, type ReactNode } from 'react';
import type { I18nText, Progress, RGBAImage, ViewId } from '../../core/types';
import { VIEW_LABELS } from '../../ai/views';
import { useI18n } from '../i18n';
import { RGBACanvas } from '../RGBACanvas';
import { ProgressBar } from '../GeneratePanel';
import { IconAlert, IconInfo, IconUpload, IconWand, IconX } from '../icons';
import { IconSettings, IconViews } from './icons';
import { OTHER_VIEW_IDS, missingViews, type OtherViewId, type ViewSlotInfo } from './types';
import './ai.css';

export const VIEW_TEXT = {
  title: { tr: 'Görünümler', en: 'Views' },
  intro: {
    tr: 'Tam 3B için her yön gerekir. Eksik görünümleri kendiniz yükleyin ya da yapay zekâya ürettirin.',
    en: 'Full 3D needs every side. Upload the missing views yourself or let AI generate them.',
  },
  count: { tr: '{n}/6 görünüm', en: '{n}/6 views' },
  source: { tr: 'Kaynak', en: 'Source' },
  uploaded: { tr: 'Yüklendi', en: 'Uploaded' },
  ai: { tr: 'AI', en: 'AI' },
  empty: { tr: 'Boş', en: 'Empty' },
  noFront: { tr: 'Önce görsel yükleyin', en: 'Upload an image first' },
  drop: { tr: 'Bırakın', en: 'Drop here' },
  upload: { tr: 'Yükle', en: 'Upload' },
  uploadView: { tr: '{view} görünümünü yükle', en: 'Upload the {view} view' },
  generate: { tr: 'AI ile üret', en: 'Generate with AI' },
  regenerate: { tr: 'AI ile yeniden üret', en: 'Regenerate with AI' },
  generateView: { tr: '{view} görünümünü AI ile üret', en: 'Generate the {view} view with AI' },
  clear: { tr: 'Temizle', en: 'Clear' },
  clearView: { tr: '{view} görünümünü temizle', en: 'Clear the {view} view' },
  generating: { tr: 'Üretiliyor…', en: 'Generating…' },
  generateMissing: { tr: 'Eksik görünümleri üret ({n})', en: 'Generate missing views ({n})' },
  allPresent: { tr: 'Tüm görünümler hazır', en: 'All views are there' },
  cancel: { tr: 'İptal', en: 'Cancel' },
  aiNotReady: { tr: 'Yapay zekâ hazır değil', en: 'AI is not ready' },
  settings: { tr: 'AI sağlayıcıları…', en: 'AI providers…' },
  manual: { tr: 'Görünümleri elle yüklemek her zaman mümkün.', en: 'You can always upload views by hand.' },
  needFront: { tr: 'Önce ön görünüm (kaynak görsel) gerekir.', en: 'The front view (source image) is needed first.' },
  errorTitle: { tr: 'Görünüm üretilemedi', en: 'Could not generate the view' },
  hintDefault: {
    tr: 'Tüm görünümler dik, ortalanmış ve aynı ölçekte olmalı. Bir kutunun üzerine gelin ya da odaklanın: hangi yönden bakıldığını gösterir.',
    en: 'All views should be upright, centred and at the same scale. Hover or focus a slot to see where its camera is.',
  },
} satisfies Record<string, I18nText>;

/** Where each view's camera is (matches the ViewId conventions in src/core/types.ts). */
export const VIEW_HINTS: Record<ViewId, I18nText> = {
  front: { tr: 'Ön: kaynak görsel, konu kameraya bakıyor.', en: 'Front: the source image, the subject facing the camera.' },
  back: { tr: 'Arka: arkadan görünüm — öznenin sol yanı görselin solunda.', en: 'Back: seen from behind — the subject’s left side on the image’s left.' },
  left: { tr: 'Sol: öznenin sol yanı (kamera öznenin solunda).', en: 'Left: the subject’s left side (camera at the subject’s left).' },
  right: { tr: 'Sağ: öznenin sağ yanı (kamera öznenin sağında).', en: 'Right: the subject’s right side (camera at the subject’s right).' },
  top: { tr: 'Üst: yukarıdan görünüm — öznenin önü görselin altında.', en: 'Top: seen from above — the subject’s front at the image bottom.' },
  bottom: { tr: 'Alt: aşağıdan görünüm — öznenin önü görselin üstünde.', en: 'Bottom: seen from below — the subject’s front at the image top.' },
};

const T = VIEW_TEXT;
const ORDER: ViewId[] = ['front', ...OTHER_VIEW_IDS];

interface Props {
  front: RGBAImage | null;
  views: Partial<Record<OtherViewId, ViewSlotInfo>>;
  onUpload: (view: OtherViewId, file: File) => void;
  onGenerate: (view: OtherViewId) => void;
  onGenerateMissing: () => void;
  onClear: (view: OtherViewId) => void;
  busy: ViewId | 'all' | null;
  progress: Progress | null;
  error: I18nText | null;
  onCancel: () => void;
  aiReady: boolean;
  aiReason: string | null;
  onOpenSettings: () => void;
  disabled?: boolean;
}

/** The first image among dropped files (or the first file). */
function droppedImage(e: DragEvent): File | null {
  const files = Array.from(e.dataTransfer.files);
  return files.find((f) => f.type.startsWith('image/')) ?? files[0] ?? null;
}

export function ViewsPanel(p: Props) {
  const { tx } = useI18n();
  const id = useId();
  const [hint, setHint] = useState<ViewId | null>(null);
  const busy = p.busy !== null;
  const lock = !!p.disabled;
  const missing = missingViews(p.views);
  const filled = (p.front ? 1 : 0) + OTHER_VIEW_IDS.length - missing.length;
  const canAi = p.aiReady && !!p.front && !busy && !lock;

  return (
    <section className="card ai-views" aria-labelledby={`${id}-title`} data-testid="views-panel">
      <div className="card-head">
        <h2 id={`${id}-title`} className="card-title">
          <IconViews /> {tx(T.title)}
        </h2>
        <span className={`pill${filled === 6 ? ' pill-live' : ''} tabular`} data-testid="views-count">
          {tx(T.count, { n: filled })}
        </span>
      </div>
      <p className="muted small">{tx(T.intro)}</p>

      {!p.aiReady && (
        <div className="ai-callout" data-testid="views-ai-reason">
          <IconInfo size={16} />
          <div className="ai-callout-body small">
            <strong>{tx(T.aiNotReady)}</strong>
            {p.aiReason && <span>{p.aiReason}</span>}
            <span className="muted">{tx(T.manual)}</span>
          </div>
          <button type="button" className="btn btn-secondary btn-sm" onClick={p.onOpenSettings} data-testid="views-settings">
            <IconSettings size={14} /> {tx(T.settings)}
          </button>
        </div>
      )}

      <ul className="ai-view-grid" aria-describedby={`${id}-hint`}>
        {ORDER.map((view) =>
          view === 'front' ? (
            <FrontSlot key={view} image={p.front} busy={p.busy === 'front'} onHint={setHint} />
          ) : (
            <ViewSlot
              key={view}
              view={view}
              info={p.views[view] ?? null}
              busy={p.busy === view || (p.busy === 'all' && !p.views[view])}
              progress={p.busy === view ? p.progress : null}
              lock={lock || busy}
              canAi={canAi}
              aiTitle={!p.aiReady ? p.aiReason ?? tx(T.aiNotReady) : !p.front ? tx(T.needFront) : undefined}
              onUpload={(f) => p.onUpload(view, f)}
              onGenerate={() => p.onGenerate(view)}
              onClear={() => p.onClear(view)}
              onHint={setHint}
            />
          ),
        )}
      </ul>

      <p id={`${id}-hint`} className="ai-view-hint small" aria-live="polite" data-testid="views-hint">
        {hint ? <ViewDiagram view={hint} size={20} /> : <IconInfo size={14} />}
        <span>{tx(hint ? VIEW_HINTS[hint] : T.hintDefault)}</span>
      </p>

      {busy ? (
        <div className="ai-run">
          <div className="generate-row">
            <button type="button" className="btn btn-primary grow" disabled aria-busy="true">
              <span className="spinner" aria-hidden="true" /> {tx(T.generating)}
            </button>
            <button type="button" className="btn btn-secondary" onClick={p.onCancel} data-testid="views-cancel">
              <IconX size={16} /> {tx(T.cancel)}
            </button>
          </div>
          <ProgressBar progress={p.progress} testId="views-progress" />
        </div>
      ) : (
        <button
          type="button"
          className="btn btn-primary btn-block"
          onClick={p.onGenerateMissing}
          disabled={!canAi || missing.length === 0}
          title={!p.aiReady ? p.aiReason ?? tx(T.aiNotReady) : !p.front ? tx(T.needFront) : undefined}
          data-testid="views-generate-missing"
        >
          <IconWand size={16} /> {missing.length ? tx(T.generateMissing, { n: missing.length }) : tx(T.allPresent)}
        </button>
      )}
      {!busy && p.aiReady && !p.front && <p className="muted small center">{tx(T.needFront)}</p>}

      {p.error && !busy && (
        <div className="alert alert-danger" role="alert" data-testid="views-error">
          <IconAlert size={18} />
          <div className="alert-body">
            <strong>{tx(T.errorTitle)}</strong>
            <p>{tx(p.error)}</p>
          </div>
        </div>
      )}
    </section>
  );
}

function SlotHead({ view }: { view: ViewId }) {
  const { tx } = useI18n();
  return (
    <div className="ai-slot-head">
      <ViewDiagram view={view} />
      <span className="ai-slot-name">{tx(VIEW_LABELS[view])}</span>
    </div>
  );
}

function OriginBadge({ kind, children }: { kind: 'source' | 'upload' | 'ai'; children: ReactNode }) {
  return <span className={`ai-origin is-${kind}`}>{children}</span>;
}

function FrontSlot({ image, busy, onHint }: { image: RGBAImage | null; busy: boolean; onHint: (v: ViewId | null) => void }) {
  const { tx } = useI18n();
  return (
    <li
      className={`ai-slot is-front${busy ? ' is-busy' : ''}`}
      aria-busy={busy || undefined}
      data-testid="view-front"
      data-filled={image ? 'true' : 'false'}
      onMouseEnter={() => onHint('front')}
      onMouseLeave={() => onHint(null)}
      title={tx(VIEW_HINTS.front)}
    >
      <SlotHead view="front" />
      <div className="ai-slot-thumb checker">
        {image ? (
          <>
            <RGBACanvas image={image} className="ai-slot-img" label={tx(VIEW_LABELS.front)} />
            <OriginBadge kind="source">{tx(T.source)}</OriginBadge>
          </>
        ) : (
          <span className="ai-slot-empty">
            <span>{tx(T.noFront)}</span>
          </span>
        )}
        {busy && (
          <span className="ai-slot-busy">
            <span className="spinner" aria-hidden="true" />
          </span>
        )}
      </div>
      <div className="ai-slot-actions">
        <span className="ai-slot-meta tabular">{image ? `${image.width} × ${image.height}` : '—'}</span>
      </div>
    </li>
  );
}

function ViewSlot({
  view,
  info,
  busy,
  progress,
  lock,
  canAi,
  aiTitle,
  onUpload,
  onGenerate,
  onClear,
  onHint,
}: {
  view: OtherViewId;
  info: ViewSlotInfo | null;
  busy: boolean;
  progress: Progress | null;
  lock: boolean;
  canAi: boolean;
  aiTitle: string | undefined;
  onUpload: (file: File) => void;
  onGenerate: () => void;
  onClear: () => void;
  onHint: (v: ViewId | null) => void;
}) {
  const { tx, lang } = useI18n();
  const [dragging, setDragging] = useState(false);
  const name = tx(VIEW_LABELS[view]);
  const nameLower = name.toLocaleLowerCase(lang === 'tr' ? 'tr-TR' : 'en-US');
  const pct = progress && typeof progress.ratio === 'number' && Number.isFinite(progress.ratio) ? Math.round(Math.min(1, Math.max(0, progress.ratio)) * 100) : null;

  const dragProps = lock
    ? {}
    : {
        onDragOver: (e: DragEvent) => {
          if (!Array.from(e.dataTransfer.types).includes('Files')) return;
          e.preventDefault();
          e.dataTransfer.dropEffect = 'copy';
          setDragging(true);
        },
        onDragLeave: () => setDragging(false),
        onDrop: (e: DragEvent) => {
          e.preventDefault();
          setDragging(false);
          const file = droppedImage(e);
          if (file) onUpload(file);
        },
      };

  return (
    <li
      className={`ai-slot${dragging ? ' is-dragging' : ''}${busy ? ' is-busy' : ''}`}
      data-testid={`view-${view}`}
      data-filled={info ? 'true' : 'false'}
      data-origin={info?.origin}
      aria-busy={busy || undefined}
      onMouseEnter={() => onHint(view)}
      onMouseLeave={() => onHint(null)}
      onFocus={() => onHint(view)}
      onBlur={() => onHint(null)}
      {...dragProps}
    >
      <SlotHead view={view} />
      <div className="ai-slot-thumb checker" title={info ? info.name : tx(VIEW_HINTS[view])}>
        {info ? (
          <>
            <RGBACanvas image={info.image} className="ai-slot-img" label={`${name}: ${info.name}`} />
            <OriginBadge kind={info.origin}>{tx(info.origin === 'ai' ? T.ai : T.uploaded)}</OriginBadge>
          </>
        ) : busy ? null : (
          <span className="ai-slot-empty">
            <IconUpload size={16} />
            <span>{dragging ? tx(T.drop) : tx(T.empty)}</span>
          </span>
        )}
        {busy && (
          <span className="ai-slot-busy">
            <span className="spinner" aria-hidden="true" />
            {pct !== null && <span className="tabular small">{pct}%</span>}
          </span>
        )}
      </div>
      <div className="ai-slot-actions">
        <label className={`icon-btn ai-slot-btn${lock ? ' is-disabled' : ''}`} title={tx(T.uploadView, { view: nameLower })} data-testid={`view-upload-${view}`}>
          <input
            type="file"
            accept="image/png,image/jpeg,image/webp,image/*"
            className="visually-hidden"
            disabled={lock}
            aria-label={tx(T.uploadView, { view: nameLower })}
            onChange={(e) => {
              const file = e.target.files?.[0];
              if (file) onUpload(file);
              e.target.value = '';
            }}
          />
          <IconUpload size={15} />
        </label>
        <button
          type="button"
          className="icon-btn ai-slot-btn is-ai"
          onClick={onGenerate}
          disabled={!canAi}
          aria-label={tx(info ? T.regenerate : T.generateView, { view: nameLower })}
          title={aiTitle ?? tx(info ? T.regenerate : T.generateView, { view: nameLower })}
          data-testid={`view-generate-${view}`}
        >
          <IconWand size={15} />
        </button>
        {info && (
          <button
            type="button"
            className="icon-btn ai-slot-btn"
            onClick={onClear}
            disabled={lock}
            aria-label={tx(T.clearView, { view: nameLower })}
            title={tx(T.clearView, { view: nameLower })}
            data-testid={`view-clear-${view}`}
          >
            <IconX size={15} />
          </button>
        )}
      </div>
    </li>
  );
}

/**
 * Tiny orientation sketch: a plan view (subject from above, facing down =
 * towards the front camera) for the four sides, an elevation for top /
 * bottom. The accent arrow is the camera looking at the subject.
 */
export function ViewDiagram({ view, size = 18 }: { view: ViewId; size?: number }) {
  const plan = view !== 'top' && view !== 'bottom';
  const camera: Record<ViewId, string> = {
    front: 'M16 31V25M13.5 27.5 16 24.5l2.5 3',
    back: 'M16 1v6M13.5 4.5 16 7.5l2.5-3',
    // The subject faces down in the sketch, so its left side is on the sketch's right.
    left: 'M31 15h-6M27.5 12.5 24.5 15l3 2.5',
    right: 'M1 15h6M4.5 12.5 7.5 15l-3 2.5',
    top: 'M16 0.5V5.5M13.5 3.5 16 6.5l2.5-3',
    bottom: 'M16 31.5v-5M13.5 28.5 16 25.5l2.5 3',
  };
  return (
    <svg className="ai-diagram" width={size} height={size} viewBox="0 0 32 32" aria-hidden="true" focusable="false">
      {plan ? (
        <g className="ai-diagram-subject">
          <circle cx="16" cy="15" r="6" />
          <path d="M14 20.2 16 23l2-2.8" />
        </g>
      ) : (
        <g className="ai-diagram-subject">
          <circle cx="16" cy="11.5" r="3.2" />
          <rect x="12.5" y="15.5" width="7" height="8.5" rx="2.5" />
        </g>
      )}
      <path className="ai-diagram-camera" d={camera[view]} />
    </svg>
  );
}
