/**
 * App state: a plain reducer (no library) plus loading / saving the
 * persisted parts. Heavy three.js objects live outside the state (see
 * useStudio); this module stays pure and Node-testable.
 *
 * Besides the 3D job it holds the AI side of the studio: the provider
 * settings (keys persisted by src/ai/settings — local or session storage,
 * never both), whether our server answered, the AI preparation options, the
 * one AI job that may run at a time (prep or view generation), the prepared
 * image awaiting Accept, the extra views with their alignment / trust and
 * pre-run consistency checks, the human analysis of the front image, and the
 * edit / rig flags of the model on screen.
 */
import type { Availability, Driver, I18nText, Lang, Mask, ParamValue, ParamValues, Progress, RGBAImage, ViewAlign, ViewId, ViewSet } from '../core/types';
import { DEFAULT_VIEW_ALIGN, defaultParams, sanitizeViewAlign } from '../core/types';
import type { FusionReport, ViewAlignment } from '../core/fusion/types';
import type { MeshStats } from '../core/mesh/stats';
import { MESH_PARAMS, type MeshMode } from '../core/mesh/options';
import type { HumanAnalysis } from '../core/human/types';
import type { AiSettings, PrepOptions, ProviderConfig, SubjectKind } from '../ai/types';
import { DEFAULT_PREP_OPTIONS } from '../ai/types';
import { DEFAULT_AI_SETTINGS, loadAiSettings, mergeServerProviders } from '../ai/settings';
import { getStyle } from '../ai/styles';
import { detectLang, type UIKey } from './i18n';
import { suggestedMeshMode } from './driverMeta';
import { isBackgroundMode, type BackgroundMode, type MaskNote, type SourceImage } from './pipeline';
import type { EnhancePlan, EnhancePresetId } from '../core/enhance/presets';
import { loadJSON, persistableParams, sanitizeParams, saveJSON, type KeyValueStore } from './persist';
import type { StepId } from './steps';

export type Theme = 'dark' | 'light';
export type JobStatus = 'idle' | 'running' | 'done' | 'error' | 'cancelled';

export interface ViewSettings {
  texture: boolean;
  wireframe: boolean;
  clay: boolean;
  autoRotate: boolean;
  darkBackground: boolean;
  showDepth: boolean;
}

export interface ResultInfo {
  driverId: string;
  kind: 'depth' | 'geometry' | 'model';
  stats: MeshStats;
  /** Grayscale preview of the depth map (depth results only). */
  depthPreview: RGBAImage | null;
  elapsedMs: number;
  sourceName: string;
  /** Multi-view fusion's consistency report (null for other drivers). */
  fusion: FusionReport | null;
  /** Views present but switched off (trust 'off') when the fusion ran; the report itself skips them. */
  fusionOff?: OtherViewId[];
}

/** The views besides the front (the front is always the source image). */
export type OtherViewId = Exclude<ViewId, 'front'>;
export const OTHER_VIEWS: OtherViewId[] = ['back', 'left', 'right', 'top', 'bottom'];

/** An extra view of the subject: uploaded or generated by AI. */
export interface ViewEntry {
  /** The file / AI output the image was decoded from (cloud drivers upload it). */
  file: Blob;
  /** Working image (longest side ≤ WORKING_MAX_SIDE). */
  image: RGBAImage;
  /** Foreground mask (alpha, plain border or AI removal); null = whole image. */
  mask: Mask | null;
  origin: 'upload' | 'ai';
  name: string;
  /** Alignment to the front (auto / manual offset, scale, flip) and what the view is trusted for. */
  align: ViewAlign;
}

export type ViewEntries = Partial<Record<OtherViewId, ViewEntry>>;

/** 'enhance': image enhancement (AI super-resolution or a local enhancer). */
export type AiJobKind = 'prep' | 'views' | 'enhance';

/** The AI job in flight (one at a time). */
export interface AiJob {
  kind: AiJobKind;
  /** Views jobs: the view being made, or 'all' for "generate the missing views". */
  target: OtherViewId | 'all' | null;
  progress: Progress | null;
}

/** An enhanced front image awaiting Apply / Discard. */
export interface EnhancePending {
  /** The new source (working image, texture copy, encoded file). */
  source: SourceImage;
  /** The front it was made from (Apply only while that is still the front). */
  from: SourceImage;
  preset: EnhancePresetId;
  /** What actually ran (the local fallback's plan when the AI could not run). */
  plan: EnhancePlan;
  /** The automatic preset fell back to the local upscaler (the AI model could not run). */
  fallback: I18nText | null;
  elapsedMs: number;
}

/** The enhancement in use: `after` is the front, `before` comes back with Revert. */
export interface EnhanceApplied {
  before: SourceImage;
  after: SourceImage;
  preset: EnhancePresetId;
}

/** Human analysis of one image: running, or its result. */
export interface HumanState {
  image: RGBAImage;
  analysis: HumanAnalysis | 'analyzing';
}

export interface AppState {
  lang: Lang;
  theme: Theme;
  /** True once the theme came from the user (stored or toggled); otherwise it follows the OS and is not persisted. */
  explicitTheme: boolean;
  source: SourceImage | null;
  loadingImage: boolean;
  bgMode: BackgroundMode;
  /** Mask for the preview overlay (and for generation in the non-AI modes). */
  mask: Mask | null;
  maskNote: MaskNote;
  /** Cached AI background-removal mask for the current source. */
  aiMask: { source: SourceImage; mask: Mask | null } | null;
  showMask: boolean;
  driverId: string;
  params: Record<string, ParamValues>;
  meshParams: ParamValues;
  /** Shown once after the mesh mode was auto-set for the selected driver. */
  meshNotice: I18nText | null;
  /**
   * Mesh mode suggested for the selected driver while a re-meshable result
   * of another run is on screen: applied by the next generation (and on its
   * jobDone) instead of silently re-meshing the displayed model. Not persisted.
   */
  pendingMeshMode: MeshMode | null;
  status: JobStatus;
  progress: Progress | null;
  error: I18nText | null;
  /** Heading for the error alert (image loading vs generation). */
  errorTitle: UIKey;
  /** The last generation failed because a model could not be downloaded (offers an offline driver; only while status is 'error'). */
  errorOffline: boolean;
  result: ResultInfo | null;
  view: ViewSettings;
  stlSizeMm: number;

  // ---- Studio steps ----
  step: StepId;

  // ---- AI ----
  aiSettings: AiSettings;
  /** Our API server answered GET /api/ai/providers (false on static hosting). */
  serverAvailable: boolean;
  /** The startup probe finished. */
  serverChecked: boolean;
  aiSettingsOpen: boolean;
  prep: PrepOptions;
  /** Image-edit provider chosen in the prep step (resolveProvider falls back when unusable). */
  aiProviderId: string | null;
  /** Human analysis of the current front image (null: not requested yet). */
  human: HumanState | null;
  aiJob: AiJob | null;
  prepError: I18nText | null;
  viewsError: I18nText | null;
  /** AI-prepared front image awaiting Accept / Discard. */
  prepared: SourceImage | null;
  /** The prep options that produced `prepared`. */
  preparedWith: PrepOptions | null;
  /**
   * The prep options that produced the current front (an accepted
   * preparation; null for an original image). Views repeat its instructions.
   */
  frontPrep: PrepOptions | null;
  /** The source before an accepted AI preparation ("Revert to original"). */
  original: SourceImage | null;
  /**
   * Undo slot of "Revert to original": the AI-prepared front and the AI views
   * made from it (paid work), restorable while the original is still the front.
   */
  revertedAi: RevertedAi | null;
  views: ViewEntries;
  /**
   * Pre-run registration of each extra view against the current front
   * (derived, computed asynchronously by useStudio; the fusion's own report
   * after a run is authoritative). Cleared when the front or the view changes.
   */
  viewChecks: Partial<Record<OtherViewId, ViewAlignment>>;

  // ---- Image enhancement (step 1) ----
  /** Enhanced image awaiting Apply / Discard. */
  enhanced: EnhancePending | null;
  /** The applied enhancement (Revert restores `before` while `after` is still the front). */
  enhanceApplied: EnhanceApplied | null;
  enhanceError: I18nText | null;

  // ---- Model edits ----
  /** Sculpt mode is on (a session owns the viewer's pointer input). */
  sculptActive: boolean;
  /** The model on screen carries sculpt edits (live re-meshing is paused). */
  sculpted: boolean;
  /**
   * The current sculpt session started on geometry that already carried sculpt
   * edits (an earlier session): undoing it back to 0 strokes does not make the
   * model unsculpted.
   */
  sculptBase: boolean;
  /** The model on screen is rigged (skinned meshes; re-mesh and sculpt are off). */
  rigged: boolean;
  depthEditorOpen: boolean;
  /** The model on screen is the result of a depth-map edit. */
  depthEdited: boolean;
  /** Generate was requested while the model carries edits: the panel asks before discarding them. */
  regenConfirm: boolean;
}

export type Action =
  | { type: 'setLang'; lang: Lang }
  | { type: 'setTheme'; theme: Theme }
  | { type: 'imageLoading' }
  | { type: 'imageLoaded'; source: SourceImage; mask: Mask | null; maskNote: MaskNote }
  | { type: 'imageFailed'; error: I18nText; title?: UIKey }
  | { type: 'clearImage' }
  | { type: 'setBgMode'; mode: BackgroundMode; mask: Mask | null; maskNote: MaskNote }
  | { type: 'setShowMask'; show: boolean }
  | { type: 'selectDriver'; driver: Driver }
  | { type: 'setParam'; driverId: string; key: string; value: ParamValue }
  | { type: 'resetParams'; driver: Driver }
  | { type: 'setMeshParam'; key: string; value: ParamValue }
  | { type: 'resetMeshParams' }
  | { type: 'jobStart' }
  | { type: 'jobProgress'; progress: Progress }
  | { type: 'jobDone'; result: ResultInfo; source: SourceImage; bgMode: BackgroundMode; inputMask: Mask | null }
  | { type: 'jobFailed'; error: I18nText; offline?: boolean }
  | { type: 'jobCancelled' }
  | { type: 'statsUpdated'; stats: MeshStats }
  | { type: 'setView'; view: Partial<ViewSettings> }
  | { type: 'dismissError' }
  | { type: 'setStlSize'; mm: number }
  // Steps
  | { type: 'setStep'; step: StepId }
  // AI settings / server
  | { type: 'setAiSettings'; settings: AiSettings }
  | { type: 'serverProbed'; providers: ProviderConfig[] | null }
  | { type: 'setAiSettingsOpen'; open: boolean }
  | { type: 'setPrep'; patch: Partial<PrepOptions> }
  | { type: 'setAiProvider'; id: string | null }
  // Human analysis
  | { type: 'humanStart'; image: RGBAImage }
  | { type: 'humanDone'; image: RGBAImage; analysis: HumanAnalysis }
  | { type: 'humanCancelled'; image: RGBAImage }
  // AI job
  | { type: 'aiJobStart'; kind: AiJobKind; target?: OtherViewId | 'all' | null }
  | { type: 'aiJobProgress'; progress: Progress }
  | { type: 'aiJobDone' }
  | { type: 'aiJobFailed'; kind: AiJobKind; error: I18nText }
  | { type: 'aiJobCancelled' }
  | { type: 'prepReady'; prepared: SourceImage; options?: PrepOptions }
  | { type: 'prepDiscard' }
  | { type: 'prepAccept'; mask: Mask | null; maskNote: MaskNote }
  | { type: 'revertOriginal'; mask: Mask | null; maskNote: MaskNote }
  | { type: 'restorePrepared'; mask: Mask | null; maskNote: MaskNote }
  | { type: 'dismissAiError'; kind: AiJobKind }
  // Image enhancement
  | { type: 'enhanceReady'; pending: EnhancePending }
  | { type: 'enhanceDiscard' }
  | { type: 'enhanceApply'; mask: Mask | null; maskNote: MaskNote }
  | { type: 'enhanceRevert'; mask: Mask | null; maskNote: MaskNote }
  // Views
  | { type: 'viewSet'; view: OtherViewId; entry: ViewEntry }
  | { type: 'viewClear'; view: OtherViewId }
  /** Patch of a view's alignment; dx / dy / scale in the patch make it manual. */
  | { type: 'viewAlign'; view: OtherViewId; patch: Partial<ViewAlign> }
  | { type: 'viewAlignAuto'; view: OtherViewId }
  | { type: 'viewAlignReset'; view: OtherViewId }
  /** Registration result; accepted only while `front` and `image` are still the current ones. */
  | { type: 'viewChecked'; view: OtherViewId; front: RGBAImage; image: RGBAImage; check: ViewAlignment }
  // Model edits
  | { type: 'setSculptActive'; active: boolean }
  | { type: 'sculptSessionStart' }
  /** `strokes`: the session's stroke count after the edit (undo / redo / reset included). */
  | { type: 'sculptEdited'; stats: MeshStats; strokes?: number }
  | { type: 'sculptDiscarded'; stats: MeshStats }
  | { type: 'setRigged'; rigged: boolean }
  | { type: 'setDepthEditor'; open: boolean }
  | { type: 'depthEdited'; stats: MeshStats; depthPreview: RGBAImage }
  | { type: 'setRegenConfirm'; open: boolean };

export const DEFAULT_VIEW: ViewSettings = {
  texture: true,
  wireframe: false,
  clay: false,
  autoRotate: false,
  darkBackground: true,
  showDepth: true,
};

export const DEFAULT_STL_SIZE_MM = 100;

const SUBJECTS: SubjectKind[] = ['auto', 'human', 'character', 'animal', 'object'];
export const MAX_EXTRA_PROMPT = 1000;

/** Valid prep options from anything stored (unknown style ids dropped, text capped). */
export function sanitizePrep(stored: unknown, base: PrepOptions = DEFAULT_PREP_OPTIONS): PrepOptions {
  const src = stored && typeof stored === 'object' ? (stored as Record<string, unknown>) : {};
  const bool = (k: 'tPose' | 'completeBody' | 'removeBackground') => (typeof src[k] === 'boolean' ? (src[k] as boolean) : base[k]);
  const styleId = 'styleId' in src ? (typeof src.styleId === 'string' && getStyle(src.styleId) ? src.styleId : null) : base.styleId;
  return {
    subject: typeof src.subject === 'string' && (SUBJECTS as string[]).includes(src.subject) ? (src.subject as SubjectKind) : base.subject,
    styleId,
    tPose: bool('tPose'),
    completeBody: bool('completeBody'),
    removeBackground: bool('removeBackground'),
    extraPrompt: typeof src.extraPrompt === 'string' ? src.extraPrompt.slice(0, MAX_EXTRA_PROMPT) : base.extraPrompt,
  };
}

/** Reset of everything tied to the previous subject (a brand-new image or none). */
const freshSubject = (): Partial<AppState> => ({
    views: {},
    viewChecks: {},
    prepared: null,
    preparedWith: null,
    frontPrep: null,
    original: null,
    revertedAi: null,
    human: null,
    aiJob: null,
    prepError: null,
    viewsError: null,
    enhanced: null,
    enhanceApplied: null,
    enhanceError: null,
});

/** The front was replaced by an AI preparation / revert: enhancement results made from the old one are stale. */
const frontReplaced: Partial<AppState> = { enhanced: null, enhanceApplied: null };

/** A new model replaced the one on screen: edits / rig belonged to the old one. */
const freshModel: Partial<AppState> = {
  sculpted: false,
  sculptActive: false,
  sculptBase: false,
  rigged: false,
  depthEditorOpen: false,
  depthEdited: false,
  regenConfirm: false,
};

/** The checks without `view`'s (the same object when there was none). */
function withoutCheck(checks: AppState['viewChecks'], view: OtherViewId): AppState['viewChecks'] {
  if (!checks[view]) return checks;
  const out = { ...checks };
  delete out[view];
  return out;
}

/** Views made by AI from the previous front: dropped when the front changes (uploads are kept). */
function withoutAiViews(views: ViewEntries): ViewEntries {
  const out: ViewEntries = {};
  for (const id of OTHER_VIEWS) {
    const v = views[id];
    if (v && v.origin !== 'ai') out[id] = v;
  }
  return out;
}

/** What "Revert to original" set aside (see AppState.revertedAi). */
export interface RevertedAi {
  source: SourceImage;
  /** The original that became the front again (restore only applies while it still is). */
  original: SourceImage;
  frontPrep: PrepOptions | null;
  aiViews: ViewEntries;
}

function aiViewsOf(views: ViewEntries): ViewEntries {
  const out: ViewEntries = {};
  for (const id of OTHER_VIEWS) if (views[id]?.origin === 'ai') out[id] = views[id];
  return out;
}

export function reducer(state: AppState, action: Action): AppState {
  switch (action.type) {
    case 'setLang':
      return { ...state, lang: action.lang };
    case 'setTheme':
      // The viewer background follows the theme (the viewer toolbar can still override it).
      return { ...state, theme: action.theme, explicitTheme: true, view: { ...state.view, darkBackground: action.theme === 'dark' } };
    case 'imageLoading':
      return { ...state, loadingImage: true, error: null };
    case 'imageLoaded':
      // A brand-new image: the views, the AI preparation and the analysis belonged to the old subject.
      return {
        ...state,
        ...freshSubject(),
        loadingImage: false,
        source: action.source,
        mask: action.mask,
        maskNote: action.maskNote,
        aiMask: null,
        error: null,
        status: state.status === 'running' ? 'running' : 'idle',
      };
    case 'imageFailed':
      return { ...state, loadingImage: false, error: action.error, errorTitle: action.title ?? 'imageErrorTitle' };
    case 'clearImage':
      // Any load still in flight is superseded (useStudio bumps its sequence) and never reports back.
      return { ...state, ...freshSubject(), source: null, mask: null, maskNote: null, aiMask: null, loadingImage: false };
    case 'setBgMode': {
      // The cached AI mask survives mode switches so going back to 'ai' is instant.
      const cached = action.mode === 'ai' && state.aiMask && state.aiMask.source === state.source ? state.aiMask : null;
      return {
        ...state,
        bgMode: action.mode,
        mask: cached ? cached.mask : action.mask,
        maskNote: cached ? null : action.maskNote,
      };
    }
    case 'setShowMask':
      return { ...state, showMask: action.show };
    case 'selectDriver': {
      const { driver } = action;
      const params = state.params[driver.id] ? state.params : { ...state.params, [driver.id]: defaultParams(driver.params) };
      if (driver.id === state.driverId) return { ...state, params, meshNotice: null };
      const mode = suggestedMeshMode(driver);
      let meshParams = state.meshParams;
      let meshNotice: I18nText | null = null;
      let pendingMeshMode: MeshMode | null = null;
      if (mode && meshParams.mode !== mode) {
        // The mesh params drive the live re-mesh of the model on screen: while a
        // depth result is shown, changing them would silently rebuild it (under
        // its old driver's label / export name). Defer to the next generation.
        if (state.result?.kind === 'depth') pendingMeshMode = mode;
        else {
          meshParams = { ...meshParams, mode };
          meshNotice = meshModeLabel(mode);
        }
      }
      return { ...state, driverId: driver.id, params, meshParams, meshNotice, pendingMeshMode };
    }
    case 'setParam': {
      const current = state.params[action.driverId] ?? {};
      return { ...state, params: { ...state.params, [action.driverId]: { ...current, [action.key]: action.value } } };
    }
    case 'resetParams':
      return { ...state, params: { ...state.params, [action.driver.id]: defaultParams(action.driver.params) } };
    case 'setMeshParam':
      return {
        ...state,
        meshParams: { ...state.meshParams, [action.key]: action.value },
        meshNotice: null,
        // An explicit mode choice wins over the pending suggestion.
        pendingMeshMode: action.key === 'mode' ? null : state.pendingMeshMode,
      };
    case 'resetMeshParams':
      return { ...state, meshParams: defaultParams(MESH_PARAMS), meshNotice: null, pendingMeshMode: null };
    case 'jobStart':
      return { ...state, status: 'running', progress: null, error: null, regenConfirm: false };
    case 'jobProgress':
      return state.status === 'running' ? { ...state, progress: action.progress } : state;
    case 'jobDone': {
      const next: AppState = { ...state, ...freshModel, status: 'done', progress: null, result: action.result };
      // generate() built the new model with the pending mode; the params follow
      // only now, so the previous model was never re-meshed while the job ran.
      if (state.pendingMeshMode) {
        next.meshParams = { ...state.meshParams, mode: state.pendingMeshMode };
        next.pendingMeshMode = null;
      }
      if (action.bgMode === 'ai') {
        next.aiMask = { source: action.source, mask: action.inputMask };
        if (state.source === action.source && state.bgMode === 'ai') {
          next.mask = action.inputMask;
          next.maskNote = null;
        }
      }
      return next;
    }
    case 'jobFailed':
      return { ...state, status: 'error', progress: null, error: action.error, errorTitle: 'errorTitle', errorOffline: !!action.offline };
    case 'jobCancelled':
      return { ...state, status: 'cancelled', progress: null };
    case 'statsUpdated':
      return state.result ? { ...state, result: { ...state.result, stats: action.stats } } : state;
    case 'setView':
      return { ...state, view: { ...state.view, ...action.view } };
    case 'dismissError':
      return { ...state, error: null, status: state.status === 'error' ? 'idle' : state.status };
    case 'setStlSize':
      return Number.isFinite(action.mm) && action.mm > 0 ? { ...state, stlSizeMm: action.mm } : state;

    case 'setStep':
      return action.step === state.step ? state : { ...state, step: action.step };

    case 'setAiSettings':
      return { ...state, aiSettings: action.settings };
    case 'serverProbed':
      return {
        ...state,
        serverChecked: true,
        serverAvailable: action.providers !== null,
        aiSettings: action.providers ? mergeServerProviders(state.aiSettings, action.providers) : state.aiSettings,
      };
    case 'setAiSettingsOpen':
      return { ...state, aiSettingsOpen: action.open };
    case 'setPrep':
      return { ...state, prep: sanitizePrep(action.patch, state.prep) };
    case 'setAiProvider':
      return { ...state, aiProviderId: action.id };

    case 'humanStart':
      return { ...state, human: { image: action.image, analysis: 'analyzing' } };
    case 'humanDone':
      // Late results for an image that is no longer the front are dropped.
      return state.source?.image === action.image ? { ...state, human: { image: action.image, analysis: action.analysis } } : state;
    case 'humanCancelled':
      return state.human?.image === action.image && state.human.analysis === 'analyzing' ? { ...state, human: null } : state;

    case 'aiJobStart':
      return {
        ...state,
        aiJob: { kind: action.kind, target: action.target ?? null, progress: null },
        prepError: action.kind === 'prep' ? null : state.prepError,
        viewsError: action.kind === 'views' ? null : state.viewsError,
        enhanceError: action.kind === 'enhance' ? null : state.enhanceError,
      };
    case 'aiJobProgress':
      return state.aiJob ? { ...state, aiJob: { ...state.aiJob, progress: action.progress } } : state;
    case 'aiJobDone':
    case 'aiJobCancelled':
      return state.aiJob ? { ...state, aiJob: null } : state;
    case 'aiJobFailed':
      return {
        ...state,
        aiJob: null,
        prepError: action.kind === 'prep' ? action.error : state.prepError,
        viewsError: action.kind === 'views' ? action.error : state.viewsError,
        enhanceError: action.kind === 'enhance' ? action.error : state.enhanceError,
      };
    case 'dismissAiError':
      if (action.kind === 'enhance') return { ...state, enhanceError: null };
      return action.kind === 'prep' ? { ...state, prepError: null } : { ...state, viewsError: null };
    case 'prepReady':
      return { ...state, aiJob: null, prepError: null, prepared: action.prepared, preparedWith: action.options ?? null, revertedAi: null };
    case 'prepDiscard':
      return { ...state, prepared: null, preparedWith: null };
    case 'prepAccept': {
      const prepared = state.prepared;
      if (!prepared || !state.source) return state;
      // The prepared image becomes the front and the first original is
      // remembered. AI views were generated from the previous front (never from
      // a pending prepared image): they no longer match it and are dropped;
      // uploaded views are kept (they may have been made for it).
      const views = withoutAiViews(state.views);
      return {
        ...state,
        views,
        viewChecks: {}, // the front changed: every registration is stale
        viewsError: null,
        source: prepared,
        original: state.original ?? state.source,
        revertedAi: null,
        prepared: null,
        preparedWith: null,
        frontPrep: state.preparedWith,
        mask: action.mask,
        maskNote: action.maskNote,
        aiMask: null,
        human: null,
        ...frontReplaced,
      };
    }
    case 'revertOriginal': {
      if (!state.original || !state.source) return state;
      return {
        ...state,
        views: withoutAiViews(state.views),
        viewChecks: {},
        viewsError: null,
        source: state.original,
        original: null,
        revertedAi: { source: state.source, original: state.original, frontPrep: state.frontPrep, aiViews: aiViewsOf(state.views) },
        frontPrep: null,
        mask: action.mask,
        maskNote: action.maskNote,
        aiMask: null,
        human: null,
        ...frontReplaced,
      };
    }
    case 'restorePrepared': {
      const r = state.revertedAi;
      if (!r || state.source !== r.original) return state;
      // Views uploaded after the revert keep their slots.
      const views: ViewEntries = { ...r.aiViews, ...state.views };
      return {
        ...state,
        views,
        viewChecks: {},
        viewsError: null,
        source: r.source,
        original: r.original,
        frontPrep: r.frontPrep,
        revertedAi: null,
        mask: action.mask,
        maskNote: action.maskNote,
        aiMask: null,
        human: null,
        ...frontReplaced,
      };
    }

    case 'enhanceReady':
      // A result for a front that has been replaced meanwhile is dropped.
      if (state.source !== action.pending.from) return { ...state, aiJob: null };
      return { ...state, aiJob: null, enhanceError: null, enhanced: action.pending };
    case 'enhanceDiscard':
      return state.enhanced ? { ...state, enhanced: null } : state;
    case 'enhanceApply': {
      const pending = state.enhanced;
      if (!pending || !state.source || pending.from !== state.source) return state;
      // The enhanced image becomes the front; the picture is the same, so every
      // view (AI-made ones too) stays, but registrations, masks and the human
      // analysis belong to the old pixels. Applying on top of an applied
      // enhancement keeps the first "before" for Revert.
      const before = state.enhanceApplied && state.enhanceApplied.after === state.source ? state.enhanceApplied.before : state.source;
      return {
        ...state,
        source: pending.source,
        enhanced: null,
        enhanceApplied: { before, after: pending.source, preset: pending.preset },
        enhanceError: null,
        viewChecks: {},
        mask: action.mask,
        maskNote: action.maskNote,
        aiMask: null,
        human: null,
      };
    }
    case 'enhanceRevert': {
      const applied = state.enhanceApplied;
      if (!applied || state.source !== applied.after) return state;
      return {
        ...state,
        source: applied.before,
        enhanced: null,
        enhanceApplied: null,
        viewChecks: {},
        mask: action.mask,
        maskNote: action.maskNote,
        aiMask: null,
        human: null,
      };
    }

    case 'viewSet':
      return { ...state, views: { ...state.views, [action.view]: action.entry }, viewChecks: withoutCheck(state.viewChecks, action.view), viewsError: null };
    case 'viewClear': {
      if (!state.views[action.view]) return state;
      const views = { ...state.views };
      delete views[action.view];
      return { ...state, views, viewChecks: withoutCheck(state.viewChecks, action.view) };
    }
    case 'viewAlign': {
      const entry = state.views[action.view];
      if (!entry) return state;
      const p = action.patch;
      // A geometric correction is a manual one; flipping changes the registered image (the check is stale).
      const manual = p.dx !== undefined || p.dy !== undefined || p.scale !== undefined;
      const align = sanitizeViewAlign({ ...entry.align, ...p, ...(manual ? { mode: 'manual' } : {}) }, entry.align);
      const viewChecks = align.flipX !== entry.align.flipX ? withoutCheck(state.viewChecks, action.view) : state.viewChecks;
      return { ...state, views: { ...state.views, [action.view]: { ...entry, align } }, viewChecks };
    }
    case 'viewAlignAuto': {
      const entry = state.views[action.view];
      if (!entry) return state;
      // A check made for a manual placement scores that placement; back in auto mode it is stale.
      const viewChecks = state.viewChecks[action.view]?.status === 'manual' ? withoutCheck(state.viewChecks, action.view) : state.viewChecks;
      return { ...state, views: { ...state.views, [action.view]: { ...entry, align: { ...entry.align, mode: 'auto', dx: 0, dy: 0, scale: 1 } } }, viewChecks };
    }
    case 'viewAlignReset': {
      const entry = state.views[action.view];
      if (!entry) return state;
      const viewChecks =
        entry.align.flipX || state.viewChecks[action.view]?.status === 'manual' ? withoutCheck(state.viewChecks, action.view) : state.viewChecks;
      return { ...state, views: { ...state.views, [action.view]: { ...entry, align: { ...DEFAULT_VIEW_ALIGN } } }, viewChecks };
    }
    case 'viewChecked':
      // Results for a front or a view image that has been replaced meanwhile are dropped.
      if (state.source?.image !== action.front || state.views[action.view]?.image !== action.image) return state;
      return { ...state, viewChecks: { ...state.viewChecks, [action.view]: action.check } };

    case 'setSculptActive':
      return state.sculptActive === action.active ? state : { ...state, sculptActive: action.active };
    case 'sculptSessionStart':
      // A new session's history starts from the geometry as it is now.
      return state.sculptBase === state.sculpted ? state : { ...state, sculptBase: state.sculpted };
    case 'sculptEdited': {
      // Back to 0 strokes (undo / reset) is the session's starting geometry.
      const sculpted = action.strokes === undefined ? true : action.strokes > 0 || state.sculptBase;
      const next: AppState = { ...state, sculpted };
      if (state.result) next.result = { ...state.result, stats: action.stats };
      return next;
    }
    case 'sculptDiscarded': {
      const next: AppState = { ...state, sculpted: false, sculptBase: false, regenConfirm: false };
      if (state.result) next.result = { ...state.result, stats: action.stats };
      return next;
    }
    case 'setRigged':
      return state.rigged === action.rigged ? state : { ...state, rigged: action.rigged };
    case 'setDepthEditor':
      return { ...state, depthEditorOpen: action.open };
    case 'depthEdited':
      return {
        ...state,
        ...freshModel,
        depthEdited: true,
        result: state.result ? { ...state.result, kind: 'depth', stats: action.stats, depthPreview: action.depthPreview } : state.result,
      };
    case 'setRegenConfirm':
      return state.regenConfirm === action.open ? state : { ...state, regenConfirm: action.open };
  }
}

/** Localised label of a mesh mode, as shown in the mesh form's select. */
export function meshModeLabel(mode: MeshMode): I18nText | null {
  const option = MESH_PARAMS.find((p) => p.key === 'mode');
  return (option?.kind === 'select' ? option.options.find((o) => o.value === mode)?.label : undefined) ?? null;
}

/** Mesh params for the next generation (the pending suggested mode applied). */
export function meshParamsForJob(state: AppState): ParamValues {
  return state.pendingMeshMode ? { ...state.meshParams, mode: state.pendingMeshMode } : state.meshParams;
}

/** Extra views present, in display order. */
export function presentViews(views: ViewEntries): OtherViewId[] {
  return OTHER_VIEWS.filter((v) => !!views[v]);
}

/** Extra views that take part in a generation (present and not switched off). */
export function activeViews(views: ViewEntries): OtherViewId[] {
  return presentViews(views).filter((v) => views[v]!.align.trust !== 'off');
}

/** The extra views as the drivers' ViewSet (the pipeline adds the front); views switched off are left out, so no driver uploads them. */
export function extraViewSet(views: ViewEntries): ViewSet {
  const out: ViewSet = {};
  for (const id of OTHER_VIEWS) {
    const v = views[id];
    if (v && v.align.trust !== 'off') out[id] = { id, image: v.image, mask: v.mask, file: v.file, origin: v.origin, align: v.align };
  }
  return out;
}

/** Why Generate cannot run (null = it can). */
export type GenerateBlock =
  | { kind: 'no-image' }
  | { kind: 'loading' }
  | { kind: 'unavailable'; reason: I18nText | null }
  | { kind: 'ai-busy' }
  /** A driver with views 'required': `missing` lists its `minViews` not given ([] = any extra view is enough). */
  | { kind: 'views'; missing: OtherViewId[] };

/**
 * Generate guard shared by the Generate button and the Ctrl/Cmd+Enter
 * shortcut: an image is loaded, no new image is being decoded, the driver is
 * not known to be unavailable ('checking' does not block), no AI job runs,
 * and drivers that require extra views have them.
 */
export function generateBlock(state: AppState, availability: Availability | 'checking' | null, driver?: Driver | null): GenerateBlock | null {
  if (!state.source) return { kind: 'no-image' };
  if (state.loadingImage) return { kind: 'loading' };
  if (availability && availability !== 'checking' && !availability.ok) return { kind: 'unavailable', reason: availability.reason ?? null };
  if (state.aiJob) return { kind: 'ai-busy' };
  if (driver?.views === 'required') {
    const active = activeViews(state.views);
    const missing = (driver.minViews ?? []).filter((v): v is OtherViewId => v !== 'front' && !active.includes(v as OtherViewId));
    if (active.length === 0 || missing.length > 0) return { kind: 'views', missing };
  }
  return null;
}

export function canGenerate(state: AppState, availability: Availability | 'checking' | null, driver?: Driver | null): boolean {
  return generateBlock(state, availability, driver) === null;
}

/** The model on screen carries work a new generation would throw away (sculpt, rig or depth edits). */
export function hasUnsavedModelEdits(state: Pick<AppState, 'sculpted' | 'rigged' | 'depthEdited'>): boolean {
  return state.sculpted || state.rigged || state.depthEdited;
}

/** Live re-meshing is paused while the model carries sculpt edits, is being sculpted or is rigged. */
export function remeshPaused(state: Pick<AppState, 'sculpted' | 'sculptActive' | 'rigged'>): boolean {
  return state.sculpted || state.sculptActive || state.rigged;
}

interface StoredSettings {
  lang?: unknown;
  theme?: unknown;
  driverId?: unknown;
  bgMode?: unknown;
  view?: unknown;
  stlSizeMm?: unknown;
  showMask?: unknown;
  aiProviderId?: unknown;
}

export interface InitEnv {
  store: KeyValueStore | null;
  /** sessionStorage: AI keys live here unless the user chose to remember them. */
  session?: KeyValueStore | null;
  languages: readonly string[] | string | undefined;
  drivers: Driver[];
  defaultDriverId: string;
  prefersLight?: boolean;
}

export const PREP_KEY = 'prep';

export function createInitialState(env: InitEnv): AppState {
  const settings = (loadJSON(env.store, 'settings') ?? {}) as StoredSettings;
  const lang: Lang = settings.lang === 'tr' || settings.lang === 'en' ? settings.lang : detectLang(env.languages);
  const explicitTheme = settings.theme === 'light' || settings.theme === 'dark';
  const theme: Theme = explicitTheme ? (settings.theme as Theme) : env.prefersLight ? 'light' : 'dark';
  const known = (id: unknown) => typeof id === 'string' && env.drivers.some((d) => d.id === id);
  const driverId = known(settings.driverId)
    ? (settings.driverId as string)
    : known(env.defaultDriverId)
      ? env.defaultDriverId
      : (env.drivers[0]?.id ?? env.defaultDriverId);
  const params: Record<string, ParamValues> = {};
  for (const d of env.drivers) params[d.id] = sanitizeParams(d.params, loadJSON(env.store, `params:${d.id}`));
  const storedView = settings.view && typeof settings.view === 'object' ? (settings.view as Record<string, unknown>) : {};
  const view: ViewSettings = { ...DEFAULT_VIEW, darkBackground: theme === 'dark' };
  for (const k of Object.keys(DEFAULT_VIEW) as (keyof ViewSettings)[]) if (typeof storedView[k] === 'boolean') view[k] = storedView[k] as boolean;
  const stl = typeof settings.stlSizeMm === 'number' && settings.stlSizeMm > 0 && settings.stlSizeMm <= 10_000 ? settings.stlSizeMm : DEFAULT_STL_SIZE_MM;
  let aiSettings: AiSettings = DEFAULT_AI_SETTINGS;
  try {
    aiSettings = loadAiSettings(env.store, env.session ?? null);
  } catch (e) {
    console.warn('[ai] could not load the provider settings', e);
  }
  return {
    lang,
    theme,
    explicitTheme,
    source: null,
    loadingImage: false,
    bgMode: isBackgroundMode(settings.bgMode) ? settings.bgMode : 'auto',
    mask: null,
    maskNote: null,
    aiMask: null,
    showMask: typeof settings.showMask === 'boolean' ? settings.showMask : false,
    driverId,
    params,
    meshParams: sanitizeParams(MESH_PARAMS, loadJSON(env.store, 'mesh')),
    meshNotice: null,
    pendingMeshMode: null,
    status: 'idle',
    progress: null,
    error: null,
    errorTitle: 'errorTitle',
    errorOffline: false,
    result: null,
    view,
    stlSizeMm: stl,
    // No image survives a reload, so every later step would open empty.
    step: 'image',
    aiSettings,
    serverAvailable: false,
    serverChecked: false,
    aiSettingsOpen: false,
    prep: sanitizePrep(loadJSON(env.store, PREP_KEY)),
    aiProviderId: typeof settings.aiProviderId === 'string' && settings.aiProviderId.length <= 64 ? settings.aiProviderId : null,
    human: null,
    aiJob: null,
    prepError: null,
    viewsError: null,
    prepared: null,
    preparedWith: null,
    frontPrep: null,
    original: null,
    revertedAi: null,
    views: {},
    viewChecks: {},
    enhanced: null,
    enhanceApplied: null,
    enhanceError: null,
    sculptActive: false,
    sculpted: false,
    sculptBase: false,
    rigged: false,
    depthEditorOpen: false,
    depthEdited: false,
    regenConfirm: false,
  };
}

/**
 * Persist settings, mesh params, the AI prep options and every driver's
 * non-secret params. The theme is saved only once the user chose it, and the
 * viewer background only when it differs from the theme's, so both keep
 * following the OS otherwise. AI provider settings are saved separately
 * (saveAiSettings: keys to exactly one of local / session storage).
 */
export function saveState(store: KeyValueStore | null, state: AppState, drivers: Driver[]): void {
  const { darkBackground, ...view } = state.view;
  saveJSON(store, 'settings', {
    lang: state.lang,
    theme: state.explicitTheme ? state.theme : undefined,
    driverId: state.driverId,
    bgMode: state.bgMode,
    view: darkBackground === (state.theme === 'dark') ? view : state.view,
    stlSizeMm: state.stlSizeMm,
    showMask: state.showMask,
    aiProviderId: state.aiProviderId ?? undefined,
  });
  saveJSON(store, 'mesh', state.meshParams);
  saveJSON(store, PREP_KEY, state.prep);
  for (const d of drivers) {
    const values = state.params[d.id];
    if (values) saveJSON(store, `params:${d.id}`, persistableParams(d.params, values));
  }
}
