/**
 * Core contracts shared by every driver, the mesh builder and the UI.
 *
 * A "driver" is one strategy for turning a 2D image into 3D. Drivers are
 * listed in a select box; each declares its own parameters (rendered
 * generically by the UI) and returns one of three result kinds:
 *
 *  - `depth`    a per-pixel depth map; the shared mesh builder turns it into a
 *               surface (relief / solid / double-sided) using MeshOptions.
 *  - `geometry` a ready three.js BufferGeometry (e.g. silhouette extrusion).
 *  - `model`    a complete binary glTF (e.g. from a cloud image-to-3D API).
 *
 * Coordinate frame for `geometry` results (and the mesh builder output):
 * +Y up, +Z towards the viewer, the image's longest side spans 2 units
 * (x ∈ [-1, 1] for landscape images), centred on the origin in X/Y.
 * UVs map (0,0) to the image's bottom-left corner.
 */
import type { BufferGeometry } from 'three';

/** Localised UI text. Every user-facing string carries both languages. */
export interface I18nText {
  tr: string;
  en: string;
}

export type Lang = keyof I18nText;

/** 8-bit RGBA image, row-major, top row first (same layout as ImageData). */
export interface RGBAImage {
  width: number;
  height: number;
  data: Uint8ClampedArray;
}

/** Foreground mask, row-major, top row first. 1 = foreground, 0 = background. */
export interface Mask {
  width: number;
  height: number;
  data: Uint8Array;
}

/**
 * Depth map, row-major, top row first.
 * Values are normalised to [0, 1] where **1 = closest to the viewer**.
 */
export interface DepthMap {
  width: number;
  height: number;
  data: Float32Array;
}

interface ParamBase {
  key: string;
  label: I18nText;
  hint?: I18nText;
}

export interface NumberParam extends ParamBase {
  kind: 'number';
  min: number;
  max: number;
  step: number;
  default: number;
}

export interface BooleanParam extends ParamBase {
  kind: 'boolean';
  default: boolean;
}

export interface SelectParam extends ParamBase {
  kind: 'select';
  options: { value: string; label: I18nText }[];
  default: string;
}

export interface TextParam extends ParamBase {
  kind: 'text';
  default: string;
  /** Render as a password field and never persist it. */
  secret?: boolean;
  placeholder?: string;
}

export type ParamSpec = NumberParam | BooleanParam | SelectParam | TextParam;
export type ParamValue = number | boolean | string;
export type ParamValues = Record<string, ParamValue>;

export interface Progress {
  label: I18nText;
  /** 0..1 when known; undefined renders an indeterminate bar. */
  ratio?: number;
}

export type DriverCategory = 'ml' | 'heuristic' | 'multiview' | 'cloud';

export type DriverBadge =
  | 'offline' // runs fully locally, no downloads
  | 'download' // downloads model weights on first use (cached afterwards)
  | 'webgpu' // accelerated by WebGPU when available (falls back to WASM)
  | 'api-key' // needs a server-side or user-supplied API key
  | 'closed-mesh' // produces a watertight mesh
  | 'full-3d' // reconstructs unseen sides (not just 2.5D)
  | 'multi-view' // uses the extra views (back / sides / top / bottom) when given
  | 'human-detail'; // refines faces / hands with landmark detection

/**
 * The six orthographic views of the subject. `front` is always the source
 * image; the others are uploaded by the user or generated by an AI provider.
 * Conventions (all views upright, subject centred, same scale):
 *  - back:   seen from behind (the subject's left is on the image's left)
 *  - left:   the subject's left side (camera at the subject's left, looking at it)
 *  - right:  the subject's right side
 *  - top:    seen from above, the subject's front at the image bottom
 *  - bottom: seen from below, the subject's front at the image top
 */
export type ViewId = 'front' | 'back' | 'left' | 'right' | 'top' | 'bottom';
export const VIEW_IDS: ViewId[] = ['front', 'back', 'left', 'right', 'top', 'bottom'];

/** What a view may contribute to a multi-view reconstruction. */
export type ViewTrust = 'full' | 'color' | 'off';

/**
 * Per-view alignment request. `mode: 'auto'`: the fusion registers the view to
 * the front itself (dx / dy / scale are ignored, kept as the UI's cached copy).
 * `mode: 'manual'`: dx / dy / scale are absolute corrections of the silhouette
 * bbox fit (see alignedBox in src/core/fusion/align.ts): dx / dy in fractions of
 * the view's longest bbox side, + = the content moves image-right / down in the
 * object frame; scale > 1 = the content counts as larger. flipX mirrors the view
 * image and mask before anything else. Applies to any mode.
 */
export interface ViewAlign {
  mode: 'auto' | 'manual';
  dx: number;
  dy: number;
  scale: number;
  flipX: boolean;
  trust: ViewTrust;
}

export const DEFAULT_VIEW_ALIGN: ViewAlign = { mode: 'auto', dx: 0, dy: 0, scale: 1, flipX: false, trust: 'full' };

/** Sanitiser limits: |dx|, |dy| ≤ offset; scaleMin ≤ scale ≤ scaleMax. */
export const VIEW_ALIGN_RANGE = { offset: 0.25, scaleMin: 0.5, scaleMax: 2 } as const;

const TRUSTS: ViewTrust[] = ['full', 'color', 'off'];

/** A valid ViewAlign from anything (unknown / non-finite fields fall back to `base`). */
export function sanitizeViewAlign(v: unknown, base: ViewAlign = DEFAULT_VIEW_ALIGN): ViewAlign {
  const src = v && typeof v === 'object' ? (v as Record<string, unknown>) : {};
  const num = (k: 'dx' | 'dy' | 'scale', lo: number, hi: number) => {
    const x = src[k];
    return typeof x === 'number' && Number.isFinite(x) ? Math.min(hi, Math.max(lo, x)) : base[k];
  };
  const r = VIEW_ALIGN_RANGE;
  return {
    mode: src.mode === 'manual' ? 'manual' : src.mode === 'auto' ? 'auto' : base.mode,
    dx: num('dx', -r.offset, r.offset),
    dy: num('dy', -r.offset, r.offset),
    scale: num('scale', r.scaleMin, r.scaleMax),
    flipX: typeof src.flipX === 'boolean' ? src.flipX : base.flipX,
    trust: typeof src.trust === 'string' && (TRUSTS as string[]).includes(src.trust) ? (src.trust as ViewTrust) : base.trust,
  };
}

export interface ViewImage {
  id: ViewId;
  /** Working image (longest side ≤ the app's working size). */
  image: RGBAImage;
  /** Foreground mask (alpha / background removal); null = whole image. */
  mask: Mask | null;
  /** The file the image came from (cloud drivers upload it). */
  file: Blob;
  origin: 'source' | 'upload' | 'ai';
  /** Alignment / trust of an extra view (absent = auto, full trust). Ignored for the front. */
  align?: ViewAlign;
}

export type ViewSet = Partial<Record<ViewId, ViewImage>>;

export interface DriverInput {
  /** Working image (already downscaled to the app's max working size). */
  image: RGBAImage;
  /** Foreground mask derived from the PNG alpha channel / background removal; null when the image is fully opaque and no removal ran. */
  mask: Mask | null;
  /** The original uploaded file (for drivers that upload it somewhere). */
  file: Blob;
  params: ParamValues;
  /**
   * Extra views of the subject (front = the source image). Always passed;
   * drivers without the 'multi-view' badge ignore it.
   */
  views: ViewSet;
  signal: AbortSignal;
  onProgress: (p: Progress) => void;
}

export type DriverResult =
  | { kind: 'depth'; depth: DepthMap; mask: Mask | null }
  /**
   * A ready geometry in the shared frame. With a `color` attribute (linear
   * RGB, itemSize 3) it is shown with vertex colours; otherwise its `uv`
   * attribute maps the source image as texture.
   */
  | { kind: 'geometry'; geometry: BufferGeometry }
  | { kind: 'model'; glb: ArrayBuffer };

export interface Availability {
  ok: boolean;
  reason?: I18nText;
}

export interface Driver {
  /** Stable id, used in URLs / persisted settings. */
  id: string;
  name: I18nText;
  description: I18nText;
  category: DriverCategory;
  badges: DriverBadge[];
  /** Approximate one-time download size, shown in the UI. */
  downloadSizeMB?: number;
  params: ParamSpec[];
  /** True when the driver returns `kind: 'depth'`, so the shared MeshOptions apply. */
  producesDepth: boolean;
  /**
   * How the driver uses the extra views: 'required' drivers need at least one
   * view besides the front (the UI blocks Generate otherwise and names
   * `minViews`), 'optional' ones use whatever is there. Omitted = ignored.
   */
  views?: 'optional' | 'required';
  /** Views (besides the front) a 'required' driver needs, e.g. ['back', 'left', 'right']. */
  minViews?: ViewId[];
  /** Optional capability check (e.g. server has an API key configured). */
  isAvailable?: () => Promise<Availability>;
  run: (input: DriverInput) => Promise<DriverResult>;
}

/** Thrown by drivers when `signal` is aborted. */
export class AbortError extends Error {
  constructor() {
    super('Aborted');
    this.name = 'AbortError';
  }
}

export function throwIfAborted(signal: AbortSignal): void {
  if (signal.aborted) throw new AbortError();
}

/** Default values for a list of params. */
export function defaultParams(specs: ParamSpec[]): ParamValues {
  const out: ParamValues = {};
  for (const s of specs) out[s.key] = s.default;
  return out;
}
